.TH ac_monitor "1" "23 Apr 2014" "tritech-utils" "Tritech Service System"

.SH NAME
ac_monitor \- Watch AC adapter status and beep on changes

.SH DESCRIPTION
.B ac_monitor
watches the first "mains" power supply found under /sys/class/power_supply
for status changes and emits a PC speaker beep when a change occurs.

.SH COPYRIGHT
tritech-utils is Copyright (C) by Jody Bruchon. See the file LICENSE for
details on the terms and conditions under which this software is licensed.
.PP
.SH AUTHOR
Jody Lee Bruchon <jody@jodybruchon.com>
