.TH tss_file_tool "1" "2 May 2014" "tritech-utils" "Tritech Service System"

.SH NAME
tss_file_tool \- Perform various checks on devices/files

.SH SYNOPSIS
\fBtss_file_tool\fP \fIcommand\fP \fI/dev/device|/path/to/file\fP \fI[hex-head-count]\fP

.SH DESCRIPTION
.B tss_file_tool
is a quick analysis and simple operation "Swiss Army knife."
.SH COMMANDS
.PP
.I id
attempts to identify the filesystem or file format of the file or device by
examining known strings in the header.
.PP
.I ntfsgeom
modifies the logical head count number in an NTFS filesystem boot sector.
Many versions of Windows require the \fIheads\fP field in an NTFS boot
sector to match the value reported by the BIOS, or Windows will not boot.
This utility simplifies changing the value, which normally requires a
hex editor or very ugly shell scripting kludges.
.PP
.SH OPTIONS
.PP
.I hex-head-count
is a two-character hexadecimal head count. Most BIOS implementations will use
\fIff\fP, some use \fIf0\fP, and some SATA add-on controller cards use \fI0f\fP
or \fI10\fP. Only used with the \fIntfsgeom\fP command.
.SH CAVEATS
In addition to this geometry correction, Windows also requires that the
geometry values in the partition table match the BIOS values. This utility
does not correct partition table entries. You will need to use \fIfdisk\fP in
expert mode with hand-calculated values for the disk's cylinders/heads/sectors
values and then recreate the partition entries, a task which is beyond the
scope of this documentation.
.PP
.SH COPYRIGHT
tritech-utils is Copyright (C) by Jody Bruchon. See the file LICENSE for
details on the terms and conditions under which this software is licensed.
.PP
.SH AUTHOR
Jody Lee Bruchon <jody@jodybruchon.com>
