.TH tt_beacon "1" "29 Oct 2013" "tritech-utils" "Tritech Service System"

.SH NAME
tt_beacon \- Broadcast a periodic UDP beacon

.SH SYNOPSIS
\fBtt_beacon\fP \fIbroadcast_address\fP \fIport\fP \fIinterval\fP \fI"beacon text string"\fP

.SH DESCRIPTION
.B tt_beacon
repeatedly sends a string to the LAN via UDP broadcast on the specified port. 
It can be used e.g. to enable simple discovery of a server without the benefit 
of any prior network-specific configuration.

.SH OPTIONS
.I broadcast_address
specifies the broadcast IP address to use. Example: if the LAN is set up 
as 192.168.100.0/24, use 192.168.100.255 as the broadcast address.
.PP
.I port
specifies the UDP port to broadcast on.
.PP
.I interval
is the delay between broadcasts in seconds.
.PP
.I "beacon text string"
is any string of text to broadcast.
.PP
.SH COPYRIGHT
tritech-utils is Copyright (C) by Jody Bruchon. See the file LICENSE for
details on the terms and conditions under which this software is licensed.
.PP
.SH AUTHOR
Jody Lee Bruchon <jody@jodybruchon.com>
