#!/bin/ash

# Version 0.2

# Set up mixers
if [ -e /usr/bin/amixer ]; then
amixer sset 'Master',0 90% unmute 2>/dev/null >/dev/null
amixer sset 'Master Mono',0 90% unmute 2>/dev/null >/dev/null
amixer sset 'Master Front',0 90% unmute 2>/dev/null >/dev/null
amixer sset 'Front',0 75% unmute 2>/dev/null >/dev/null
amixer sset 'PCM',0 90% unmute 2>/dev/null >/dev/null
amixer sset 'Headphone',0 90% unmute 2>/dev/null >/dev/null
amixer sset 'Surround',0 90% unmute 2>/dev/null >/dev/null
amixer sset 'Beep',0 100% unmute 2>/dev/null >/dev/null
amixer sset 'PC Speaker',0 100% unmute 2>/dev/null >/dev/null
amixer sset 'Speaker',0 100% unmute 2>/dev/null >/dev/null
fi

