#!/bin/ash

# Outputs the file version for Windows PE executables

test ! -e "$1" && echo "File $1 does not exist." && exit 1

cat "$1" | tr \\x0 "~" | \
  sed s/~~/\\n/g | \
  sed s/FileVersion~/FileVersion\\n/g | \
  tr -d "~" | sed s/built/\\nbuilt/g | \
  strings | grep -A 1 FileVersion \
  | tail -n 1
