#!/bin/bash

# Mounts the Tritech CIFS source share to /mnt/cifs

VER=2.0.1
VERDATE="2017-05-30"

. tss__common

V=2
test "$1" = "-c" && V=1
test "$1" = "-q" && V=0

# Load TSS client to get CIFS configuration details
TSSC_AUTO=0; TSSC_FORCE=1
. tss_client

# Cache mode must be loose for certain 3.x kernel versions
# At some point this was fixed (works fine with 3.18.5)
unset CACHE LOOSE
test $(uname -r | cut -d. -f1) -eq 3 && \
	test $(uname -r | cut -d. -f2) -gt 4 && \
	test $(uname -r | cut -d. -f2) -lt 16 && \
	CACHE=",cache=loose" && LOOSE="$CYEL (loose cache)$COFF"

test "$V" = "2" && \
	echo "${CWHT}TSS CIFS automount version $CGRN$VER$CWHT, updated $CGRN$VERDATE$COFF"

# Check for CIFS mount helper (required)
if ! mount.cifs -V 2>/dev/null >/dev/null
	then echo "${CWHT}mount.cifs$CRED required but not found.$COFF"
	exit 1
fi

if [[ "$1" = "-h" || "$1" = "--help" ]]
	then
	echo "Usage:"
	echo "$0 -c"
	echo "   Print critical information, be less verbose"
	echo "$0 -q"
	echo "   Quiet mode, only returns exit status"
	echo "$0 -s config_string"
	echo "   Force a manual configuration in the following format:"
	echo "   cifs:ip.addr.of.server/share:username:password"
	echo "   Ex.: $0 -s \"cifs:10.10.0.4/tss:tssuser:SuperSecret\""
	exit 2
fi

# See if we are already mounted and don't waste any time if we are
# This is the default because the beacon wastes time when already mounted
mount | grep -q "on /mnt/cifs type" && echo "${CWHT}/mnt/cifs ${CYEL}already mounted$COFF" && exit

TEMP=$(mktemp)
rm -f $TEMP

# Beacon and server config functionality moved to TSS client

# Handle manual configuration if one was passed
if [ "$1" = "-s" ]
	then
	test "$2" = "" && echo "${CRED}-s option specified without a string$COFF" && exit 2
	RAW="$2"
	SVRX="$(echo $RAW | sed s/cifs:// | sed s/:.*//g)"
	SVR="$(echo "$SVRX" | sed 's/\/.*//')"
	UN="$(echo $RAW | sed s/cifs:[^:]*:// | sed s/\:.*//)"
	PW="$(echo $RAW | sed s/cifs:.*://)"
	HARDCODED=1

	else
	detect_tss_server
	SVRX="$TSS_CIFS_BASE"
	SVR="$TSS_SERVER"
	UN="$TSS_CIFS_UN"
	PW="$TSS_CIFS_PW"
	HARDCODED="$TSS_CIFS_HC"
fi

# Sanity check: can't proceed if there is no server value at all
if [[ "$SVRX" = "" || "$UN" = "" ]]
	then
	test $V -gt 1 && echo "${CRED}Error in data, info: cifs:$SVRX:$UN:$PW$COFF"
	exit 1
fi

# Verify the share string has a slash in it
if ! echo "$SVRX" | grep -q /
	then
	echo "${CRED}Server string seems invalid: $SVRX$COFF"
	exit 1
fi

# Ping the server. If unreachable, try until we time out.
TIMEOUT=3

if [ "$HARDCODED" != "1" ]
	then
	if ! ping -c 1 -W 1 $SVR >/dev/null 2>/dev/null
		then test "$V" = "2" && echo -n "${CYEL}Trying to reach $SVR: $COFF"
		X=$TIMEOUT; Y=0
		while [ "$X" -gt "0" ]
			do test "$V" -gt "0" && echo -n "${CWHT}${X}${COFF} "
			if ! ping -c 1 -W 1 $SVR >/dev/null 2>/dev/null
				then X=$((X - 1))
				else Y=1
			fi
			test "$Y" -eq "1" && break
			sleep 1
			if [ "$X" -eq "0" ]
				then echo "${CRED}failed.${COFF}"; exit 1
			fi
		done
	fi

	if ! ping -c 1 -W 1 $SVR >/dev/null 2>/dev/null
		then test "$V" = "2" && \
			echo "${CRED}All pings to server $SVR timed out.${COFF}"
		exit 1
	fi
fi

test "$V" = "2" && echo -n "${CYEL}Mounting...$COFF"

TESTLINE=$(mount | grep "on /mnt/cifs type")
if [ ! "$TESTLINE" = "" ]
	then
	if echo $TESTLINE | cut -d" " -f1 | grep -q "$SVRX"
		then
		test "$V" -gt "0" && echo "$CGRN$SVRX $CWHT=>$CGRN /mnt/cifs (already mounted)$COFF"
		exit

		else
		test "$V" -gt "0" && echo "${CRED}/mnt/cifs is used by a different mount; aborting.$COFF"
		exit 1
	fi
fi

# Try a SMB3 mount if possible for better performance
if mount -t cifs -o vers=3.0,user="$UN",pass="$PW"$CACHE //$SVRX /mnt/cifs 2>/dev/null >/dev/null
	then
	test "$V" -gt "0" && echo "$CGRN$SVRX $CWHT=>$CGRN /mnt/cifs ${CWHT}(SMB 3.0)$LOOSE$COFF"
	exit
fi

# Fall back to default CIFS mount command and options
# Added cache=loose due to default change causing breakage in kernels >3.6.11
if mount.cifs //$SVRX /mnt/cifs -o user="$UN",pass="$PW"$CACHE 2>/dev/null >/dev/null
	then
	test "$V" -gt "0" && echo "$CGRN$SVRX $CWHT=>$CGRN /mnt/cifs ${CYEL}(SMB1/2)$LOOSE$COFF"
	exit
	else test "$V" -gt "0" && echo "${CRED}failed.$COFF"
	exit 1
fi

