#!/bin/bash

# Show CPU temperature

VER=1.0.2
VERDATE=2016-06-29

shopt -s nullglob

. tss__common
unset THRM
for X in $THERMAL_SOURCES
	do
	if [ -e "$X" ]
		then THRM="$X"
		test "$1" = "-v" && echo "using $X" >&2
	fi
done

# These thresholds may need to change in the future
TEMP_YELLOW=68
TEMP_RED=78
TEMP_BOGUS=110
N_OVERHEAT=0

if [ -e "$THRM" ]
	then CPUTEMP="$(expr $(cat "$THRM") / 1000)"
	echo -n "CPU temp: $CGRN"
	test $CPUTEMP -gt $TEMP_YELLOW && echo -n "$CYEL"
	test $CPUTEMP -gt $TEMP_RED && test $CPUTEMP -lt 100 && echo -n "$CRED"
	test $CPUTEMP -ge $TEMP_BOGUS && echo -n "$CPUR"
	echo "$CPUTEMP${CWHT} C$COFF"
	else echo "No CPU temperature sensor available."
fi
