#!/bin/bash

VER="5.7.2"
VERDATE="2017-04-18"

# Tritech Service System Windows installation clean tool for Linux
# Copyright (C) by Jody Bruchon <jody@jodybruchon.com>

# Must be run from the root of the filesystem to clean.

. tss__common
test -z "$TSS_COMMON" && echo "Library 'tss__common' failed to load, aborting." && exit 1
. tss_client
test -z "$TSS_CLIENT_VER" && \
	echo "${CYEL}NOTICE: ${CWHT}TSS client missing, can't record cleaning action$COFF"

IFS0="$IFS"
IFS1=$(echo -en "\n\b")
IFS="$IFS1"
CLEANED=0
RW=0
FB_ADD=0
LASTTYPE="none"
TMPFILE=$(mktemp)
shopt -s nullglob
shopt -s nocaseglob
shopt -s nocasematch

control_c () {
	rm -f "$TMPFILE"
	test $MSG -gt 0 && echo -e "\nAborted by user. Cleaned $CLEANED KB."
	exit 1
}

trap control_c INT

# Initialize some settings
NODEL=0; MSG=2; DEBUG=0; NOSIZE=0
unset FORCED NOREPORT

# Parse command line parameters
for X in $@
	do if [[ "$X" = "-h" || "$X" = "--help" ]]
		then
		PN="$(basename $0)"
		echo -e "Tritech Service System Cleaner, a junk cleaning tool for Linux\n"
		echo "Program version $VER, last updated on $VERDATE"
		echo "$PN         normal mode, shows verbose scan progress and reports"
		echo "$PN -x      fast normal mode, skips size counts of cleaned items"
		echo "$PN -q      quiet mode, with progress dots and a summary"
		echo "$PN -Q      fast quiet mode, with progress but no summary"
		echo "$PN -s      silent mode, no output, returns an exit code"
		echo "$PN -n      normal mode, but don't actually delete anything"
		echo "$PN -d      debug mode: -n, plus shows what would be deleted"
		echo "$PN -h      this help screen"
		echo "$PN --help  this help screen with four wasted keystrokes"
		echo -e "\nCopyright (C) Jody Bruchon <jody@jodybruchon.com>"
		exit 0
	fi
	# Change parameters for different command switches
	# MSG: 0=none, 1=quiet, 2=full
	# NODEL: 0=delete, 1=no delete
	# NOSIZE: 0=get size of cleaned items, 1=skip calculation (faster)
	test "$X" = "-s" && MSG=0 && NOSIZE=1
	test "$X" = "-q" && MSG=1
	test "$X" = "-Q" && MSG=1 && NOSIZE=1
	test "$X" = "-x" && MSG=2 && NOSIZE=1
	test "$X" = "-n" && MSG=2 && NODEL=1
	test "$X" = "-d" && MSG=2 && NODEL=1 && DEBUG=1
	# Allow forcing the OS selection and directories
	test "$X" = "--xp" && export V7=1 && FORCED=1
	test "$X" = "--v7" && export V7=2 && FORCED=1
	test "$X" = "--osx" && export OSX=1 && FORCED=1
	test "$X" = "--no-report" && NOREPORT=1
done

test $DEBUG -gt 0 && unset CWHT CGRN CPUR CCYA CYEL CRED CBLU

### Scan for 2000/XP or Vista/7 or Mac OS X and set folders accordingly
export V7=0
export OSX=0
export UPF=0
export LOCAL=__NONE__
export ROAM=__NONE__
export LIBRARY=__NONE__
OSYS="None"

# Skip OS structure checks if forced
if [ -z "$FORCED" ]
	then
	test -d "$XPDOCS" && export V7=1 && export UPF=1
	if [ -d "$V7DOCS" ]
		then export V7=2 && export UPF=1
		# XPREDO is for if a non-symlink XPDOCS exists
		test -e "$XPDOCS" && test ! -h "$XPDOCS" && XPREDO=1
	fi
	if [[ -d "System/Library" || -d "Users/Shared/Library" ]]
		then export OSX=1 && export V7=0
		test -d "Users/Shared/Library" && export UPF=1
	fi
fi

if [ "$V7" = "1" ]
	then
	OSYS="Windows 2000/XP"
	export P="$XPDOCS/*"
	export LOCAL="$P/$XPLOCAL"
	export ROAM="$P/$XPROAM"
fi
if [ "$V7" = "2" ]
	then
	OSYS="Windows Vista/7/8.x/10"
	export P="$V7DOCS/*"
	export LOCAL="$P/$V7LOCAL"
	export ROAM="$P/$V7ROAM"
fi
if [ "$OSX" = "1" ]
	then
	OSYS="Mac OS X"
	export P="Users/*"
	export LIBRARY="$P/Library"
fi
test "$FORCED" = "1" && OSYS="$OSYS (forced)"

# Scan version of P for grep-friendliness
SCANP="$(echo "$P" | sed 's#\*#\[\^/\]\*#g')"
### End OS version scan

### Common variables and locations

APPLE="Apple Computer"
APPLEIC="Apple/Installer Cache"
APPLEIC2="$APPLE/Installer Cache"
APPLELOGS="$APPLE/Logs"
APPLEMSB="$APPLE/MobileSync/Backup"
APPLEIPSW="$APPLE/iTunes/*Software Updates"
APPLEIPLG="$APPLE/iTunes/*Updater Logs"
APPLESN="$APPLE/SyncNotifier/SyncNotifier/Logs"
CARBONITEUS="Carbonite Restored OLD User Settings"
JAVACACHE="Sun/Java/Deployment/cache"
JSYSCACHE="Sun/Java/Deployment/SystemCache"
MBAMLOGS="Malwarebytes/Malwarebytes\' Anti-Malware/Logs"
MBAMQUAR="Malwarebytes/Malwarebytes\' Anti-Malware/Quarantine"
MOZCNTRL="MozillaControl/profiles/MozillaControl/*"
MPARTCACHE="$MS/Media Player/Art Cache"
MPTRANSC="$MS/Media Player/Transcoded Files Cache"
MSSQLLOG="$MS SQL Server/*/Setup Bootstrap/LOG"
PARETOAS="ParetoLogic Anti-Spyware"
PHOTOEXP="Nova Development/Photo Explosion*/*"
SAFARI="Apple Computer/Safari"
SAVCELOGS='Symantec/Symantec AntiVirus Corporate Edition/*/Logs'
STARTMENU="Microsoft/Windows/Start Menu/Programs"
SPYBOTSD="Spybot - Search & Destroy/Logs"
V7HIST1="Microsoft/Windows/History/History.IE5"
V7HIST2="Microsoft/Windows/History/Low/History.IE5"
V7SAMPLE="Public/*/Sample */"
WDSMART="Western Digital/WD SmartWare"
WINDEF="Windows Defender"
WLPG="$MS/Windows Live Photo Gallery"
YMSGR="Yahoo!/Messenger"

### End common variables

test "$MSG" = "1" && echo -n "Cleaning: "
if [ "$MSG" = "2" ]
	then echo -e "${CWHT}Tritech Service System Cleaner, version $CGRN$VER$COFF ($CGRN$VERDATE$COFF)"
	echo "${CWHT}OS detected: $OSYS$COFF"
	test $V7 -gt 0 && test "$WINDIR" = "__NONE__" && \
		echo "${CYEL}NOTICE: ${CWHT}No Windows folder detected$COFF"
	test "$UPF" = "0" && echo "${CYEL}NOTICE: ${CWHT}No user profile root folder detected$COFF"
fi

### Functions

escape_regex () {
	for CHAR in \. \[ \] \^ \$
		do RXS="$(echo "$RXS" | sed "s/\\${CHAR}/\\\\${CHAR}/g")"
	done
	RXS="$(echo "$RXS" | sed 's/\?/\./g')"
	RXS="$(echo "$RXS" | sed 's/\*/\.\*/g')"
}

# Check the name being added against a list of protected paths
test_protected () {
	for Q in $P $LOCAL $ROAM $XPDOCS $WINDIR $PF \
	$V7DOCS $V7LL $PD $XPLS $LOCAL/Temp/smtmp $LOCAL/temp/smtmp
		do
		test "$ADD" = "$Q" && echo "$ADD = $Q, ABORTING." && exit 1
	done
}

add_to_wipe () {
	for ADD in $NAME
		do
		if [ -d "$ADD" ]
			then
			test_protected
			do_wipe
			else
			test -e "$ADD" && test "$DEBUG" = "1" && echo "WARNING: Is a file: $ADD"
		fi
	done
	test ! "$RW" = "1" && RW_W=1 && do_rewrites && unset RW_W
}

do_wipe () {
# Run requested wipes
for FILE in $ADD
	do if [ -d "$FILE" ]
		then IFS="$IFS0"
		# Don't bother with empty directories but watch for hidden ones
		if [ $(ls -1a "$FILE/" | wc -l) -gt 2 ]
			then
			if [ "$NOSIZE" = "0" ]
				then
				ADD=$(du -s -- "$FILE" 2>/dev/null | cut -f1)
				CLEANED=$(( CLEANED + ADD ))
			fi
			for E in "$FILE"
				do
				test "$NODEL" = "0" && rm -rf -- "$E" 2>/dev/null && mkdir "$FILE" 2>/dev/null
				test "$DEBUG" = "1" && echo "\"$E\" "
			done
			CLEAN_TYPE="$DESC"
			do_feedback
		fi
	fi
	IFS="$IFS1"
done
}

add_to_delete () {
	for ADD in $NAME
		do
		if [ -e "$ADD" ]
			then
			do_delete
			DELETE=( "${DELETE[@]}" "$ADD" )
			DEL_DESC=( "${DEL_DESC[@]}" "$DESC" )
		fi
	done
	test ! "$RW" = "1" && RW_D=1 && do_rewrites && unset RW_D
}

do_delete () {
# Run requested deletes
for FILE in $ADD
	do
	       	if [ -e "$FILE" ]
		then
		if [ "$NOSIZE" = "0" ]
			then
			ADD=$(du -s -- "$FILE" | cut -f1)
			CLEANED=$(( CLEANED + ADD ))
		fi
		for E in "$FILE"
			do test "$NODEL" = "0" && rm -rf -- "$E" 2>/dev/null
			test "$DEBUG" = "1" && echo " \"$E\" "
		done
		CLEAN_TYPE="$DESC"
		do_feedback
	fi
done
}

add_to_scan () {
#	RXS="$NAME"; escape_regex; NAME="$RXS"
#	RXS="$SP"; escape_regex; SP="$RXS"
# Run requested scans
for FILE in $(grep -i "^${SP}/" $TMPFILE | grep -i "/${NAME}\$")
	do if [ -e "$FILE" ]
		then
		if [ "$NOSIZE" = "0" ]
			then
			ADD=$(du -s -- "$FILE" | cut -f1)
			CLEANED=$(( CLEANED + ADD ))
		fi
		for E in "$FILE"
		 do test "$NODEL" = "0" && rm -f -- "$E" 2>/dev/null
		 test "$DEBUG" = "1" && echo " \"$E\" "
		done
		CLEAN_TYPE="$DESC"
		do_feedback
	fi
done

}

do_feedback () {
	test "$MSG" = "1" && echo -n "$CWHT.$COFF"
	if [ "$MSG" = "2" ]
		then
		if [ ! "$LASTTYPE" = "$CLEAN_TYPE" ]
			then
			echo -en "\n"
			FB_ADD=0
		fi
		echo -en "\r"
		printf "%-35s" "$CGRN$CLEAN_TYPE:"
		if [ "$NOSIZE" = "0" ]
			then FB_ADD=$((FB_ADD + ADD))
			echo -n "$CWHT${FB_ADD}K $COFF"
		fi
		LASTTYPE="$CLEAN_TYPE"
	fi
}

# Rewrites are necessary due to things being put in different locations
# under Windows Vista/7 and occasionally being found in more than
# one location, as in the SYSTEM profile not being under the usual
# user account folder.
do_rewrites () {
	if ! [[ "$RW_W" = "1" || "$RW_D" = "1" ]]
		then echo -e "\nERROR: Rewrites called without RW_W or RW_D set: $NAME $DESC"
	fi
	RWIDX=${#REWRITE0[@]}
	RWCNT=0; RWLOAD=0
	unset RWNAMES
	RWNAMES[0]="$NAME"
	# The outer loop processes each rewrite in order
	# Each run of the inner loop processes previous rewrites to ensure
	# that all rewrite operations happen as specified on all targets
	while [ $RWCNT -lt $RWIDX ]
		do
		RWNIDX=${#RWNAMES[@]}; RWNCNT=0
		# Inner loop for rewrite name stack processing
		while [ $RWNCNT -lt $RWNIDX ]
			do
#			if echo "${RWNAMES[$RWNCNT]}" | grep -qi "${REWRITE0[$RWCNT]}"
			if [[ "${RWNAMES[$RWNCNT]}" =~ .*${REWRITE0[$RWCNT]}.* ]]
				then
				(( RWLOAD ++ ))
				SED1="${REWRITE1[$RWCNT]}"
				SED2="${REWRITE2[$RWCNT]}"
#				NAMEX="$(echo "${RWNAMES[$RWNCNT]}" | sed "s.$SED1.$SED2.")"
				# New name processing (faster but uglier)
				NAME_ORIG="${RWNAMES[$RWNCNT]}"
				SED1="${SED1/^/}"
				SED1="${SED1//\\/}"
				NAME="${NAME_ORIG/"$SED1"/"$SED2"}"
#				test "$NAMEX" != "$NAME" && echo -e "\nRW mismatch:\nOld  $NAMEX\nNew  $NAME\nOrig $NAME_ORIG\nSED1 $SED1\nSED2 $SED2"
				# End of new name processing
				test ! "$NAME" == "${RWNAMES[$RWNCNT]}" && \
				 RWNAMES=( "${RWNAMES[@]}" "$NAME" )
				# RW=1 tells routines to not do rewrites again while running nested
				RW=1
				test "$RW_W" = "1" && add_to_wipe
				test "$RW_D" = "1" && add_to_delete
				RW=0
			fi
			(( RWNCNT ++ ))
		done
	(( RWCNT ++ ))
	done
}

### End functions

test "$DEBUG" = "1" && echo "Debug mode active. Load bars and colors are off."

### Define what and how to clean

# Rewrites
# REWRITE0 is a grep regex to match
# REWRITE1 and REWRITE2 are part of a sed replacement expression

# Vista sometimes uses LocalLow instead of Local
if [ "$V7" = "2" ]; then
	REWRITE0=( "${REWRITE0[@]}" "AppData/Local/" )
	REWRITE1=( "${REWRITE1[@]}" "AppData/Local/" )
	REWRITE2=( "${REWRITE2[@]}" "AppData/LocalLow/" )
fi

# Vista moved All Users roaming data to ProgramData
if [ "$V7" = "2" ]; then
	# ROAM contains an unescaped asterisk which throws off matching
	ROAM2=$(echo "$ROAM" | sed 's.*.\\*.g')
	REWRITE0=( "${REWRITE0[@]}" "$ROAM2" )
	REWRITE1=( "${REWRITE1[@]}" "$ROAM2" )
	REWRITE2=( "${REWRITE2[@]}" "$PD" )
fi

# Apply user profile cleaning to SYSTEM profile too
if ! [ "$SYS32" = "__NONE__" ]; then
	REWRITE0=( "${REWRITE0[@]}" "$P" )
	REWRITE1=( "${REWRITE1[@]}" "$P" )
	REWRITE2=( "${REWRITE2[@]}" "$WINDIR/$SYS32/$CONFIG/$SYSPROF" )
fi

# Windows Vista/7 use ServiceProfiles folders for service profiles
if [ -e "$WINDIR/ServiceProfiles" ]; then
	REWRITE0=( "${REWRITE0[@]}" "^$P" )
	REWRITE1=( "${REWRITE1[@]}" "^$P" )
	REWRITE2=( "${REWRITE2[@]}" "$WINDIR/ServiceProfiles/*" )
fi

# For 64-bit Windows, copy System32 operations to SysWOW64
if ! [ "$SYS64" = "__NONE__" ]; then
	REWRITE0=( "${REWRITE0[@]}" "$WINDIR/$SYS32" )
	REWRITE1=( "${REWRITE1[@]}" "$WINDIR/$SYS32" )
	REWRITE2=( "${REWRITE2[@]}" "$WINDIR/$SYS64" )
fi

# Vista virtualizes Program Files to VirtualStore
if [ "$V7" = "2" ]; then
	REWRITE0=( "${REWRITE0[@]}" "$PF" )
	REWRITE1=( "${REWRITE1[@]}" "$PF" )
	REWRITE2=( "${REWRITE2[@]}" "$LOCAL/$VS/$PF" )
fi

# 64-bit to 32-bit Program Files rewrite
if ! [ "$SYS64" = "__NONE__" ]; then
	REWRITE0=( "${REWRITE0[@]}" "$PF/" )
	REWRITE1=( "${REWRITE1[@]}" "$PF" )
	REWRITE2=( "${REWRITE2[@]}" "$PF (x86)" )
fi

if ! [ "$WINDIR" = "__NONE__" ]; then
	REWRITE0=( "${REWRITE0[@]}" "$WINDIR" )
	REWRITE1=( "${REWRITE1[@]}" "$WINDIR" )
	REWRITE2=( "${REWRITE2[@]}" "$LOCAL/$VS/$WINDIR" )
fi

if [ "$V7" = "2" ]; then
	REWRITE0=( "${REWRITE0[@]}" "$PD" )
	REWRITE1=( "${REWRITE1[@]}" "$PD" )
	REWRITE2=( "${REWRITE2[@]}" "$LOCAL/$VS/$PD" )
fi

if ls $(echo "$P/$CARBONITEUS") >/dev/null 2>/dev/null; then
	REWRITE0=( "${REWRITE0[@]}" "^$P" )
	REWRITE1=( "${REWRITE1[@]}" "^$P" )
	REWRITE2=( "${REWRITE2[@]}" "$P/$CARBONITEUS" )
fi

# Try to apply XP-style folders on V7, just in case...
if ! [ "$V7" = "2" ]; then
	REWRITE0=( "${REWRITE0[@]}" "$V7ROAM" )
	REWRITE1=( "${REWRITE1[@]}" "$V7ROAM" )
	REWRITE2=( "${REWRITE2[@]}" "$XPROAM" )
	REWRITE0=( "${REWRITE0[@]}" "$V7LOCAL" )
	REWRITE1=( "${REWRITE1[@]}" "$V7LOCAL" )
	REWRITE2=( "${REWRITE2[@]}" "$XPLOCAL" )
# This last one slows down everything significantly. Not sure if we want it.
#	REWRITE0=( "${REWRITE0[@]}" "^$P" )
#	REWRITE1=( "${REWRITE1[@]}" "^$P/" )
#	REWRITE2=( "${REWRITE2[@]}" "Documents and Settings/" )
fi

# Try to catch extra stuff on Mac OS X too
#if [ "$OSX" = "1" ]
#	then
#	REWRITE0=( "${REWRITE0[@]}" "Library" )
#	REWRITE1=( "${REWRITE1[@]}" "Library" )
#	REWRITE2=( "${REWRITE2[@]}" "Library/Caches" )
#fi


########### Start Windows cleaning definitions ############

if [ $V7 -gt 0 ]; then
NAME="$LOCAL/AOL/*/toolbarCache"; DESC="AOL Caches"; add_to_wipe
NAME="$LOCAL/AOL/*/browserCache"; DESC="AOL Caches"; add_to_wipe
NAME="$LOCAL/ars.cache"; DESC="Miscellanous junk"; add_to_delete
NAME="$LOCAL/census.cache"; DESC="Miscellanous junk"; add_to_delete
NAME="$LOCAL/$APPLE/QuickTime/downloads"; DESC="QuickTime downloads"; add_to_wipe
NAME="$LOCAL/$APPLE/iTunes/Cache.db"; DESC="iTunes cache"; add_to_delete
NAME="$LOCAL/$APPLESN"; DESC="Apple SN logs"; add_to_wipe
NAME="$LOCAL/Adobe/Air/Logs"; DESC="Adobe AIR"; add_to_wipe
NAME="$LOCAL/Adobe/AIR/Logs"; DESC="Adobe AIR"; add_to_wipe
NAME="$LOCAL/Adobe/Acrobat/*/Updater"; DESC="Adobe Acrobat"; add_to_wipe
NAME="$LOCAL/Adobe/Acrobat/*/Cache"; DESC="Adobe Acrobat"; add_to_wipe
NAME="$LOCAL/Adobe/Reader*/Setup Files"; DESC="Adobe Acrobat"; add_to_wipe
NAME="$LOCAL/Adobe/Updater*"; DESC="Adobe Acrobat"; add_to_wipe
NAME="$LOCAL/alotappbar"; DESC="ALOT Toolbar"; add_to_wipe
NAME="$LOCAL/Amazon */Data/*Cache"; DESC="Amazon Caches"; add_to_wipe
NAME="$LOCAL/AMD/Fuel/ClientProxyLog*"; DESC="AMD FUEL logs"; add_to_delete
NAME="$LOCAL/AppGraffiti"; DESC="AppGraffiti"; add_to_wipe
NAME="$LOCAL/AskToolbar"; DESC="Ask Toolbar"; add_to_wipe
NAME="$LOCAL/AskSBar"; DESC="Ask Toolbar"; add_to_wipe
NAME="$LOCAL/AVG Secure Search/cache"; DESC="AVG Secure Search"; add_to_wipe
NAME="$LOCAL/AVG Web TuneUp/IE/tmp"; DESC="AVG Web TuneUp"; add_to_wipe
NAME="$LOCAL/Backup Assistant Plus/BackupLog"; DESC="Backup Assistant Plus"; add_to_wipe
NAME="$LOCAL/BearShare"; DESC="BearShare"; add_to_wipe
NAME="$LOCAL/bearsharemediabartb"; DESC="BearShare Media Bar"; add_to_wipe
NAME="$LOCAL/BibleTB"; DESC="BibleTB spyware"; add_to_wipe
NAME="$LOCAL/adaware"; DESC="Blekko Toolbar"; add_to_wipe
NAME="$LOCAL/blekkotb*"; DESC="Blekko Toolbar"; add_to_wipe
NAME="$LOCAL/BrowseForChange"; DESC="BrowseForChange"; add_to_wipe
NAME="$LOCAL/centurytoolbartb"; DESC="CenturyLink Toolbar"; add_to_wipe
NAME="$LOCAL/Conduit"; DESC="Conduit"; add_to_wipe
NAME="$LOCAL/Corel/Thumbs"; DESC="Corel Thumbs"; add_to_wipe

# Google Chrome definitions, now with less redundancy
DESC="Google Chrome"
for CHROME in "Google/Chrome/User Data" "speed browser/User Data"
	do CHROME="$LOCAL/$CHROME"
	NAME="$CHROME/*/*Cache*/"; add_to_wipe
	NAME="$CHROME/*/*Cookies"; add_to_delete
	NAME="$CHROME/*/Extensions/Temp"; add_to_wipe
	NAME="$CHROME/*/Favicons"; add_to_delete
	NAME="$CHROME/*/File System"; add_to_delete
	NAME="$CHROME/*/*History*"; add_to_delete
	NAME="$CHROME/*/JumpListIcons*"; add_to_wipe
	NAME="$CHROME/*/Last Session"; add_to_delete
	NAME="$CHROME/*/Last Tabs"; add_to_delete
	NAME="$CHROME/*/Local Storage/http*"; add_to_delete
	NAME="$CHROME/*/Media Cache"; add_to_wipe
	NAME="$CHROME/*/Pepper Data/Shockwave Flash"; add_to_wipe
	NAME="$CHROME/*/*Tabs"; add_to_delete
	NAME="$CHROME/*/Transport Security"; add_to_delete
	NAME="$CHROME/*/Thumbnails"; add_to_delete
	NAME="$CHROME/*/Visited Links"; add_to_delete
	NAME="$CHROME/*/*.tmp"; add_to_delete
	NAME="$CHROME/*.tmp"; add_to_delete
	NAME="$CHROME/Safe Browsing*"; add_to_delete
done

NAME="$LOCAL/Conduit"; DESC="Conduit software"; add_to_wipe
NAME="$LOCAL/ConduitEngine"; DESC="Conduit software"; add_to_wipe
NAME="$LOCAL/CouponAlert*"; DESC="CouponAlert"; add_to_wipe
NAME="$LOCAL/Corel*/Thumbs"; DESC="Corel thumbnails"; add_to_wipe
NAME="$LOCAL/Corel PaintShop Pro/*/Thumbs"; DESC="Corel thumbnails"; add_to_wipe
NAME="$LOCAL/Corel Photo Album"; DESC="Corel Photo Album"; add_to_wipe
NAME="$LOCAL/CrashDumps"; DESC="App crash dumps"; add_to_wipe
NAME="$LOCAL/CurseClient/CurseClient.log"; DESC="CurseClient"; add_to_delete
NAME="$LOCAL/dd_vcredist*.txt"; DESC="MSVC++ logs"; add_to_delete
NAME="$LOCAL/DataMngr"; DESC="DataMngr garbage"; add_to_wipe
NAME="$LOCAL/Diagnostics"; DESC="Windows Diagnostics"; add_to_wipe
NAME="$LOCAL/DictionaryBoss*"; DESC="DictionaryBoss"; add_to_wipe
NAME="$LOCAL/Dropbox/logs"; DESC="Dropbox"; add_to_wipe
NAME="$LOCAL/Dropbox/Update"; DESC="Dropbox"; add_to_wipe
NAME="$ROAM/Dropbox/Update"; DESC="Dropbox"; add_to_wipe
NAME="$LOCAL/DVDVideoSoftTB"; DESC="DVDVideoSoftTB"; add_to_wipe
NAME="$LOCAL/ElevatedDiagnostics"; DESC="Windows Diagnostics"; add_to_wipe
NAME="$LOCAL/Evernote/Evernote/Logs"; DESC="Evernote"; add_to_wipe
NAME="$LOCAL/Evernote/Evernote/AutoUpdate/*.exe"; DESC="Evernote"; add_to_delete
NAME="$LOCAL/EMBARQTOOLBAR"; DESC="Embarq Toolbar"; add_to_wipe
NAME="$LOCAL/Facebook/Messenger/fbmessenger.cache"; DESC="FB Messenger cache"; add_to_wipe
NAME="$LOCAL/Flixster/WebData/Cache"; DESC="Flixster"; add_to_wipe
NAME="$LOCAL/FontCache*.dat"; DESC="User font cache"; add_to_delete
NAME="$LOCAL/GDIPFONTCACHEV1.DAT"; DESC="User font cache"; add_to_delete
NAME="$LOCAL/Foxit PhantomPDF/msilog"; DESC="Foxit PhantomPDF"; add_to_wipe
NAME="$LOCAL/FunWebProducts"; DESC="FunWebProducts"; add_to_wipe
NAME="$LOCAL/Funmoods"; DESC="Funmoods"; add_to_wipe
NAME="$LOCAL/GamingWonderland"; DESC="GamingWonderland"; add_to_wipe
NAME="$LOCAL/Geckofx/1.9/*/*Cache*"; DESC="Gecko runtime"; add_to_wipe
NAME="$LOCAL/Google/Chrome Frame"; DESC="Google Chrome Frame"; add_to_wipe
NAME="$LOCAL/Google/Google Desktop/*/*.cf1"; DESC="Google Desktop"; add_to_delete
NAME="$LOCAL/Google/Google Desktop/*/*.ht1"; DESC="Google Desktop"; add_to_delete
NAME="$LOCAL/Google/Google Desktop/*/db*"; DESC="Google Desktop"; add_to_delete
NAME="$LOCAL/Google/Google Desktop/*/safeweb"; DESC="Google Desktop"; add_to_delete
NAME="$LOCAL/Google/GoogleEarth/webdata"; DESC="Google Earth"; add_to_wipe
NAME="$LOCAL/Google/GoogleEarth/unified_cache_*"; DESC="Google Earth"; add_to_wipe
NAME="$LOCAL/Google/GoogleEarth/dbCache*"; DESC="Google Earth"; add_to_delete
NAME="$LOCAL/Google/Picasa2/db3/*thumbs*.db"; DESC="Picasa"; add_to_delete
NAME="$LOCAL/Google/Picasa2/db3/preview*.db"; DESC="Picasa"; add_to_delete
NAME="$LOCAL/Google/Picasa2/cache"; DESC="Picasa"; add_to_wipe
NAME="$LOCAL/Google/Toolbar"; DESC="Google Toolbar"; add_to_wipe
NAME="$LOCAL/Google/Toolbar Cache"; DESC="Google Toolbar"; add_to_wipe
NAME="$LOCAL/Google/Toolbar History"; DESC="Google Toolbar"; add_to_wipe
NAME="$LOCAL/Google/Toolbar/metrics_*.xml"; DESC="Google Toolbar"; add_to_delete
NAME="$LOCAL/Graboid/Cache"; DESC="Graboid"; add_to_wipe
NAME="$LOCAL/Graboid/logs"; DESC="Graboid"; add_to_wipe
NAME="$LOCAL/HP Guide/mp_cache"; DESC="HP files"; add_to_wipe
NAME="$LOCAL/HP/AtInstall"; DESC="HP files"; add_to_wipe
NAME="$LOCAL/Hotbar"; DESC="Hotbar"; add_to_wipe
NAME="$LOCAL/Hot_MP3"; DESC="Hot_MP3 Toolbar"; add_to_wipe
NAME="$LOCAL/IconCache*.db"; DESC="Icon cache DB"; add_to_delete
NAME="$LOCAL/I. d. l. e . C. r. a. w. l. e. r"; DESC="Idle Crawler VIRUS"; add_to_wipe
NAME="$LOCAL/iLivid"; DESC="iLivid"; add_to_wipe
NAME="$LOCAL/ilividtoolbarguid"; DESC="iLivid"; add_to_wipe
NAME="$LOCAL/iMesh"; DESC="iMesh"; add_to_wipe
NAME="$LOCAL/imeshmediabartb"; DESC="iMesh"; add_to_wipe
NAME="$LOCAL/Inbox Toolbar"; DESC="Inbox Toolbar"; add_to_wipe
NAME="$LOCAL/InboxAce_*"; DESC="InboxAce Toolbar"; add_to_wipe
NAME="$LOCAL/Installer/Installcr_*"; DESC="Installer Adware"; add_to_wipe
NAME="$LOCAL/Installer/Installiwebar_*"; DESC="Installer Adware"; add_to_wipe
NAME="$LOCAL/Intuit/QuickBooks*/Log"; DESC="Intuit logs"; add_to_wipe
NAME="$LOCAL/Intuit/Common/Authorization/*/Logs"; DESC="Intuit logs"; add_to_wipe
NAME="$LOCAL/iWon*"; DESC="iWon software"; add_to_wipe
NAME="$LOCAL/join.me/*.log"; DESC="LMI join.me logs"; add_to_delete
NAME="$LOCAL/$JAVACACHE"; DESC="Java"; add_to_wipe
NAME="$LOCAL/$JSYSCACHE"; DESC="Java"; add_to_wipe
NAME="$LOCAL/Live_TV"; DESC="Live_TV spyware"; add_to_wipe
NAME="$LOCAL/LogMeIn Rescue Applet"; DESC="LogMeIn Rescue"; add_to_wipe
NAME="$LOCAL/lptmp*"; DESC="LastPass"; add_to_wipe
NAME="$LOCAL/LogiShrd/Vid"; DESC="Logitech Vid cache"; add_to_wipe
NAME="$LOCAL/MapsGalaxy*"; DESC="MapsGalaxy Toolbar"; add_to_wipe
NAME="$LOCAL/Mobogenie"; DESC="Mobogenie"; add_to_wipe

for MOZPROF in "Mozilla" "Mozilla/Firefox" "Thunderbird" \
	"Moonchild Productions/Pale Moon" "LimeWire/mozilla-profile" \
	"Fast Browser/*" "Fast Web Browser/*"
	do MOZPROF="$LOCAL/$MOZPROF/Profiles/*"
	DESC="Mozilla applications"
	NAME="$MOZPROF/_CACHE_*_"; add_to_delete
	NAME="$MOZPROF/urlclassifier3.sqlite"; add_to_delete
	NAME="$MOZPROF/X*.mfl"; add_to_delete
	NAME="$MOZPROF/minidumps"; add_to_wipe
	NAME="$MOZPROF/thumbnails"; add_to_wipe
	NAME="$MOZPROF/*Cache*"; add_to_wipe
done

NAME="$LOCAL/$MPARTCACHE"; DESC="WMP cache"; add_to_wipe
NAME="$LOCAL/$MPTRANSC"; DESC="WMP cache"; add_to_wipe
NAME="$LOCAL/$MS/BingBar"; DESC="Bing Bar"; add_to_wipe
NAME="$LOCAL/$MS/CD Burning"; DESC="CD Burning folder"; add_to_wipe
NAME="$LOCAL/$MS/CryptnetUrlCache"; DESC="MS crypto cert cache"; add_to_wipe
NAME="$LOCAL/$MS/Feeds Cache"; DESC="MS feeds cache"; add_to_wipe
NAME="$LOCAL/$MS/$IE/DOMStore"; DESC="IE DOMStore"; add_to_wipe
NAME="$LOCAL/$MS/$IE/Recovery"; DESC="IE session recovery"; add_to_wipe
NAME="$LOCAL/$MS/Media Player/Cache*"; DESC="Windows Media Player"; add_to_wipe
NAME="$LOCAL/$MS/Media Player/lastplayed.wpl"; DESC="Windows Media Player"; add_to_delete
NAME="$LOCAL/$MS/OneDrive/logs"; DESC="MS SkyDrive/OneDrive"; add_to_wipe
NAME="$LOCAL/$MS/OneDrive/setup/logs"; DESC="MS SkyDrive/OneDrive"; add_to_wipe
NAME="$LOCAL/$MS/SkyDrive/setup/logs"; DESC="MS SkyDrive/OneDrive"; add_to_wipe
NAME="$LOCAL/$MS/Windows/SkyDrive/logs"; DESC="MS SkyDrive/OneDrive"; add_to_wipe
NAME="$LOCAL/$MS/OneNote/*/TemporaryOneNoteOfflineCache.onecache"; DESC="MS OneNote cache"; add_to_delete
NAME="$LOCAL/$MS/OfficeStarter"; DESC="Microsoft Office"; add_to_wipe
NAME="$LOCAL/$MS/OIS"; DESC="Microsoft OIS"; add_to_wipe
NAME="$LOCAL/$MS/SmartScreen"; DESC="MS SmartScreen"; add_to_wipe
NAME="$LOCAL/$MS/Silverlight"; DESC="MS Silverlight"; add_to_wipe
NAME="$LOCAL/$MS/Toolbar"; DESC="MS Toolbar"; add_to_wipe
NAME="$LOCAL/$MS/Windows/Burn"; DESC="Windows CD/DVD burn cache"; add_to_wipe
NAME="$LOCAL/$MS/Windows/Explorer/ThumbCacheToDelete"; DESC="Explorer thumbnails"; add_to_wipe
NAME="$LOCAL/$MS/Windows/Explorer/iconcache*.db"; DESC="Explorer thumbnails"; add_to_delete
NAME="$LOCAL/$MS/Windows/Explorer/thumbcache*.db"; DESC="Explorer thumbnails"; add_to_delete
NAME="$LOCAL/$MS/Windows/History"; DESC="Temporary Internet Files"; add_to_wipe
NAME="$LOCAL/$MS/Windows/$TIF"; DESC="Temporary Internet Files"; add_to_wipe
NAME="$LOCAL/$MS/Windows/WebCache"; DESC="Temporary Internet Files"; add_to_wipe
NAME="$LOCAL/$MS/Windows/WER"; DESC="Windows Error Reporting"; add_to_wipe
NAME="$LOCAL/$MS/Windows NT/NTBackup"; DESC="NTBackup data"; add_to_wipe
NAME="$LOCAL/$MS/Windows Store/Cache Medium IL"; DESC="Windows Store"; add_to_wipe
NAME="$LOCAL/Packages/WinStore_*/AC/$MS/Windows Store/Cache"; DESC="Windows Store"; add_to_wipe
NAME="$LOCAL/Packages/WinStore_*/AC/$MS/Windows Store/Data/history.dat"; DESC="Windows Store"; add_to_delete
NAME="$LOCAL/Packages/*/TempState"; DESC="Windows UWP App Caches"; add_to_wipe
NAME="$LOCAL/Packages/*/AC/Temp"; DESC="Windows UWP App Caches"; add_to_wipe
NAME="$LOCAL/Packages/*/LocalState/Cache"; DESC="Windows UWP App Caches"; add_to_wipe
NAME="$LOCAL/Packages/*/AC/#!*/Cache"; DESC="Windows UWP App Caches"; add_to_wipe
NAME="$LOCAL/Packages/*/AC/#!*/INet*"; DESC="Windows UWP App Caches"; add_to_wipe
NAME="$LOCAL/Packages/*/AC/#!*/Temp"; DESC="Windows UWP App Caches"; add_to_wipe
NAME="$LOCAL/Packages/*/AC/#!*/*/Cache"; DESC="Windows UWP App Caches"; add_to_wipe
NAME="$LOCAL/Packages/*/AC/#!*/*/INet*"; DESC="Windows UWP App Caches"; add_to_wipe
NAME="$LOCAL/Packages/*/AC/#!*/*/Cookies"; DESC="Windows UWP App Caches"; add_to_wipe
NAME="$LOCAL/Packages/*/AC/#!*/*/Temp"; DESC="Windows UWP App Caches"; add_to_wipe
NAME="$LOCAL/Packages/*/AC/#!*/Microsoft/CryptnetUrlCache"; DESC="Windows UWP App Caches"; add_to_wipe
NAME="$LOCAL/Packages/*/AC/$MS/Windows/Internet Explorer"; DESC="Windows UWP App Caches"; add_to_wipe
NAME="$LOCAL/Packages/*/AC/AppCache"; DESC="Windows UWP App Caches"; add_to_wipe
NAME="$LOCAL/Packages/*/AC/INetCache"; DESC="Windows UWP App Caches"; add_to_wipe
NAME="$LOCAL/Packages/*/AC/INetCookies"; DESC="Windows UWP App Caches"; add_to_wipe
NAME="$LOCAL/Packages/*/AC/INetHistory"; DESC="Windows UWP App Caches"; add_to_wipe
NAME="$LOCAL/$MS/Windows/AppCache"; DESC="Windows 8+ TIFs"; add_to_wipe
NAME="$LOCAL/$MS/Windows/INetCache/Low/IE"; DESC="Windows 8+ TIFs"; add_to_wipe
NAME="$LOCAL/$MS/Windows/INetCache/Low/*.tmp"; DESC="Windows 8+ TIFs"; add_to_delete
NAME="$LOCAL/$MS/Windows/INetCache/IE"; DESC="Windows 8+ TIFs"; add_to_wipe
NAME="$LOCAL/$MS/Windows/INetCookies"; DESC="Windows 8+ TIFs"; add_to_wipe
NAME="$LOCAL/$MS/Windows/Notifications"; DESC="Windows Notifications"; add_to_delete
NAME="$LOCAL/$MS/Windows/WindowsUpdate.log"; DESC="Windows Update log"; add_to_delete
NAME="$LOCAL/$MS/$WINDEF/FileTracker"; DESC="Windows Defender"; add_to_wipe
NAME="$LOCAL/Musicmatch/Jukebox/Cache"; DESC="Musicmatch Jukebox cache"; add_to_wipe
NAME="$LOCAL/MyScrapNook*"; DESC="MyScrapNook"; add_to_wipe
NAME="$LOCAL/MyFunCards*"; DESC="MyFunCards"; add_to_wipe
NAME="$LOCAL/MyWebSearch"; DESC="MyWebSearch"; add_to_wipe
NAME="$LOCAL/NCH"; DESC="NCH spyware"; add_to_wipe
NAME="$LOCAL/Nero/MobileSync.Thumbnails"; DESC="Nero MobileSync"; add_to_wipe
NAME="$LOCAL/NowUSeeItPlayer"; DESC="NowUSeeItPlayer"; add_to_wipe
NAME="$LOCAL/ooVoo_Video_Chat"; DESC="ooVoo Toolbar"; add_to_wipe
NAME="$LOCAL/oovootoolbar"; DESC="ooVoo Toolbar"; add_to_wipe
NAME="$LOCAL/Oberon Games/*/cache"; DESC="Oberon Games"; add_to_wipe
NAME="$LOCAL/OpenCandy"; DESC="OpenCandy downloader"; add_to_wipe
NAME="$LOCAL/Opera/*/cache"; DESC="Opera caches"; add_to_wipe
NAME="$LOCAL/OLYMPUS/OLYMPUS Data/cache"; DESC="Olympus cache"; add_to_wipe
NAME="$LOCAL/PageRage"; DESC="PageRage data"; add_to_wipe
NAME="$LOCAL/PCHealth"; DESC="PCHealth data"; add_to_wipe
NAME="$LOCAL/PokerStars*/ImgCache"; DESC="PokerStars cache"; add_to_wipe
NAME="$LOCAL/PriceGong"; DESC="PriceGong"; add_to_wipe
NAME="$LOCAL/Productivity_*"; DESC="Productivity Toolbar"; add_to_wipe
NAME="$LOCAL/Produtools_Manuals_*"; DESC="Produtools Toolbar"; add_to_wipe
NAME="$LOCAL/RebateInformer"; DESC="RebateInformer"; add_to_wipe
NAME="$LOCAL/RecipeHub_*"; DESC="RecipeHub"; add_to_wipe
NAME="$LOCAL/Retrogamer_*"; DESC="Retrogamer"; add_to_wipe
NAME="$LOCAL/$SAFARI/Cache.db"; DESC="Safari"; add_to_delete
NAME="$LOCAL/$SAFARI/Downloads.plist"; DESC="Safari"; add_to_delete
NAME="$LOCAL/$SAFARI/History.plist"; DESC="Safari"; add_to_delete
NAME="$LOCAL/$SAFARI/History"; DESC="Safari"; add_to_wipe
NAME="$LOCAL/$SAFARI/LastSession.plist"; DESC="Safari"; add_to_delete
NAME="$LOCAL/$SAFARI/SafeBrowsing.db"; DESC="Safari"; add_to_delete
NAME="$LOCAL/$SAFARI/LocalStorage"; DESC="Safari"; add_to_wipe
NAME="$LOCAL/$SAFARI/Webpage Previews"; DESC="Safari"; add_to_wipe
NAME="$LOCAL/searchqutoolbar"; DESC="Searchqu Toolbar"; add_to_wipe
NAME="$LOCAL/searchresultstb"; DESC="Search Results Toolbar"; add_to_wipe
NAME="$LOCAL/SearchProtect"; DESC="SearchProtect"; add_to_wipe
NAME="$LOCAL/Shareaza/Incomplete"; DESC="Shareaza incompletes"; add_to_wipe
NAME="$LOCAL/ShopAtHome"; DESC="ShopAtHome"; add_to_wipe
NAME="$LOCAL/ShoppingReport*"; DESC="ShoppingReport"; add_to_wipe
NAME="$LOCAL/simppulltoolbar"; DESC="Simppull Toolbar"; add_to_wipe
NAME="$LOCAL/SiteRanker"; DESC="SiteRanker"; add_to_wipe
NAME="$LOCAL/SlimWare Utilities Inc"; DESC="SlimWare Utilities"; add_to_wipe
NAME="$LOCAL/Spotify/Browser"; DESC="Spotify"; add_to_wipe
NAME="$LOCAL/Spotify/Data"; DESC="Spotify"; add_to_wipe
NAME="$LOCAL/Spotify/Storage"; DESC="Spotify"; add_to_wipe
NAME="$LOCAL/SquirrelTemp"; DESC="Discord SquirrelTemp"; add_to_wipe
NAME="$LOCAL/SupportSoft"; DESC="SupportSoft"; add_to_wipe
NAME="$LOCAL/Sweetpacks*"; DESC="Sweetpacks"; add_to_wipe
NAME="$LOCAL/$SAVCELOGS"; DESC="Symantec AV logs"; add_to_wipe
NAME="$LOCAL/SupportSoft/DellSupportCenter/family/data/*.tmp"; DESC="Dell Support Center"; add_to_delete
NAME="$LOCAL/TelevisionFanatic"; DESC="TelevisionFanatic"; add_to_wipe
NAME="$LOCAL/*.tmp"; DESC="Temporary files"; add_to_delete
NAME="$LOCAL/temp"; DESC="Temporary files"; add_to_wipe
NAME="$LOCAL/Temp"; DESC="Temporary files"; add_to_wipe
NAME="$LOCAL/TEMP"; DESC="Temporary files"; add_to_wipe
NAME="$LOCAL/Tific"; DESC="Tific"; add_to_wipe
NAME="$LOCAL/Toolbar4"; DESC="Toolbar4"; add_to_wipe
NAME="$LOCAL/TotalRecipeSearch_*"; DESC="TotalRecipeSearch toolbar"; add_to_wipe
NAME="$LOCAL/Topix"; DESC="Tific"; add_to_wipe
NAME="$LOCAL/Trusteer/Rapport/user/logs"; DESC="Trusteer Rapport"; add_to_wipe
NAME="$LOCAL/Unity/WebPlayer/Cache"; DESC="Unity WebPlayer cache"; add_to_wipe
NAME="$LOCAL/Vafmusic9"; DESC="Vafmusic9"; add_to_wipe
NAME="$LOCAL/verizontb"; DESC="Verizon Toolbar"; add_to_wipe
NAME="$LOCAL/VisualBee*"; DESC="VisualBee"; add_to_wipe
NAME="$LOCAL/$VS/$WIN/*.tmp"; DESC="Windows temp files (VS)"; add_to_delete
NAME="$LOCAL/$V7HIST1"; DESC="IE history"; add_to_wipe
NAME="$LOCAL/$V7HIST2"; DESC="IE history"; add_to_wipe
NAME="$LOCAL/Vuze_Remote"; DESC="Vuze Remote spyware"; add_to_wipe
NAME="$LOCAL/Wajam"; DESC="Wajam"; add_to_wipe
NAME="$ROAM/$STARTMENU/Wajam"; DESC="Wajam"; add_to_wipe
NAME="$LOCAL/$WDSMART/.txt"; DESC="WD SmartWare"; add_to_delete
NAME="$LOCAL/WeatherAlerts"; DESC="WeatherAlerts"; add_to_wipe
NAME="$LOCAL/WhiteSmoke_*"; DESC="WhiteSmoke Toolbar"; add_to_wipe
NAME="$LOCAL/Windows Live/.cache"; DESC="Windows Live cache"; add_to_wipe
NAME="$LOCAL/$WLPG"; DESC="WL Photo Gallery"; add_to_wipe
NAME="$LOCAL/$MS/WLSetup"; DESC="Windows Live setup"; add_to_wipe
NAME="$LOCAL/$MS/Windows Live/Setup"; DESC="Windows Live setup"; add_to_wipe
NAME="$LOCAL/Yahoo! Companion"; DESC="Yahoo Companion"; add_to_wipe
NAME="$LOCAL/YuMp3"; DESC="YuMp3 Toolbar"; add_to_wipe
NAME="$LOCAL/Zango"; DESC="Zango"; add_to_wipe
NAME="$LOCAL/Zoom_Downloader"; DESC="Zoom Downloader"; add_to_wipe
NAME="$LOCAL/Zynga"; DESC="Zynga"; add_to_wipe


NAME="$PF/24x7Help"; DESC="24x7 Help"; add_to_wipe
NAME="$PF/A* Software/Avast*/DATA/log"; DESC="Avast Antivirus"; add_to_wipe
NAME="$PF/A* Software/Avast*/Setup/*.log"; DESC="Avast Antivirus"; add_to_delete
NAME="$PF/ATI/CIM/Reports/Report.xml.*.xml"; DESC="ATI CIM reports"; add_to_delete
NAME="$PF/Babylon"; DESC="Babylon toolbar"; add_to_wipe
NAME="$PF/Common Files/System/SysMenu*.dll"; DESC="SysMenu adware"; add_to_delete
NAME="$PF/Common Files/Windows Live/.cache"; DESC="WL cache"; add_to_wipe
NAME="$PF/Citrix/GoToMyPC/*.log"; DESC="GoToMyPC logs"; add_to_delete
NAME="$PF/DriverRestore"; DESC="DriverRestore"; add_to_delete
NAME="$PF/DriverUpdate"; DESC="DriverUpdate"; add_to_delete
NAME="$PF/Google/CrashReports"; DESC="Google Crash Reports"; add_to_wipe
NAME="$PF/Hewlett-Packard/Documentation"; DESC="HP documentation"; add_to_delete
NAME="$PF/HP/Temp"; DESC="HP temporary files"; add_to_wipe
NAME="$PF/Inbox Toolbar"; DESC="Inbox Toolbar"; add_to_wipe
NAME="$PF/Instant Support"; DESC="Instant Support"; add_to_wipe
NAME="$PF/InstantSupport"; DESC="Instant Support"; add_to_wipe
NAME="$PF/LimeWire/*.log"; DESC="LimeWire error logs"; add_to_delete
NAME="$PF/MapsGalaxy_*"; DESC="MapsGalaxy"; add_to_wipe
NAME="$PF/Mozilla*/install.log"; DESC="Mozilla install logs"; add_to_delete
NAME="$PF/MyWebSearch/bar/Cache"; DESC="MyWebSearch bar cache"; add_to_wipe
NAME="$PF/$MSSQLLOG"; DESC="MSSQL Setup Logs"; add_to_wipe
NAME="$PF/NortonInstaller"; DESC="Norton Installer"; add_to_wipe
NAME="$PF/NowUSeeItPlayer"; DESC="NowUSeeItPlayer"; add_to_wipe
NAME="$PF/PCAcceleratePro"; DESC="PCAcceleratePro"; add_to_wipe
NAME="$PF/PCAPDownloader"; DESC="PCAcceleratePro"; add_to_wipe
NAME="$PF/PCFixSpeed"; DESC="PCFixSpeed"; add_to_wipe
NAME="$PF/PCTechHotline"; DESC="PCTechHotline"; add_to_wipe
NAME="$PF/Rhapsody/radfile.rcf"; DESC="Rhapsody"; add_to_delete
NAME="$PF/Online Services"; DESC="Online Services"; add_to_wipe
NAME="$PF/OpenSoftwareUpdater"; DESC="OpenSoftwareUpdater"; add_to_wipe
NAME="$PF/Spyware Clear"; DESC="Spyware Clear"; add_to_wipe
NAME="$PF/Strongvault Online Backup"; DESC="Strongvault Backup"; add_to_wipe
NAME="$PF/TelevisionFanatic"; DESC="TelevisionFanatic"; add_to_wipe
NAME="$PF/Trend Micro/Internet Security/Log"; DESC="Trend Micro logs"; add_to_wipe
NAME="$PF/Wajam"; DESC="Wajam"; add_to_wipe
NAME="$PF/WajIntEnhance"; DESC="Wajam"; add_to_wipe
NAME="$PF/Windows Media Player/grillaprice"; DESC="GorillaPrice"; add_to_wipe
NAME="$PF/$YMSGR/cache"; DESC="Yahoo Messenger"; add_to_wipe
NAME="$PF/$YMSGR/Cache"; DESC="Yahoo Messenger"; add_to_wipe
NAME="$PF/$YMSGR/imvcache"; DESC="Yahoo Messenger"; add_to_wipe
NAME="$PF/$YMSGR/logs"; DESC="Yahoo Messenger"; add_to_wipe
NAME="$PF/$YMSGR/Logs"; DESC="Yahoo Messenger"; add_to_wipe


NAME="$ROAM/24x7 Help"; DESC="24x7 Help"; add_to_wipe
NAME="$ROAM/$STARTMENU/24x7 Help"; DESC="24x7 Help"; add_to_wipe
NAME="$ROAM/Lavasoft/Ad-Aware/Logs"; DESC="Ad-Aware"; add_to_wipe
NAME="$ROAM/Lavasoft/Ad-Aware/Quarantine"; DESC="Ad-Aware"; add_to_wipe
NAME="$ROAM/AdwareAlert/Log"; DESC="AdwareAlert"; add_to_wipe
NAME="$ROAM/AdwareAlert/Quarantine"; DESC="AdwareAlert"; add_to_wipe
NAME="$ROAM/Adobe/ARM"; DESC="Adobe ARM"; add_to_wipe
NAME="$ROAM/Adobe/*/*/ARM"; DESC="Adobe ARM"; add_to_wipe
NAME="$ROAM/AOL/*/spool"; DESC="AOL"; add_to_wipe
NAME="$ROAM/AOL/*/bart"; DESC="AOL"; add_to_wipe
NAME="$ROAM/AOL/*/misc/temp"; DESC="AOL"; add_to_wipe
NAME="$ROAM/AOL/TopSpeed/*/cache.db"; DESC="AOL"; add_to_delete
NAME="$ROAM/AOL Downloads"; DESC="AOL"; add_to_wipe
NAME="$ROAM/A* Software/Avast*/Cache"; DESC="Avast Antivirus"; add_to_wipe
NAME="$ROAM/A* Software/Avast*/chest"; DESC="Avast Antivirus"; add_to_wipe
NAME="$ROAM/A* Software/Avast*/log"; DESC="Avast Antivirus"; add_to_wipe
NAME="$ROAM/A* Software/Avast*/report"; DESC="Avast Antivirus"; add_to_wipe
NAME="$ROAM/A* Software/Persistent Data/Avast/Logs"; DESC="Avast Antivirus"; add_to_wipe
NAME="$ROAM/$APPLEIC"; DESC="Apple installer cache"; add_to_wipe
NAME="$ROAM/$APPLEIC2"; DESC="Apple installer cache"; add_to_wipe
NAME="$ROAM/$APPLEIPSW"; DESC="Apple software updates"; add_to_wipe
NAME="$ROAM/$APPLEIPLG"; DESC="Apple install logs"; add_to_wipe
NAME="$ROAM/$APPLELOGS"; DESC="Apple app logs"; add_to_wipe
NAME="$ROAM/$APPLEMSB"; DESC="Apple MobileSync backup"; add_to_wipe
NAME="$ROAM/Sammsoft/ARO/Version 2011"; DESC="Sammsoft ARO"; add_to_wipe

NAME="$ROAM/AskPartnerNetwork"; DESC="Ask Partner Network"; add_to_wipe
NAME="$ROAM/Auslogics/*/Logs"; DESC="Auslogics"; add_to_wipe
NAME="$ROAM/Avery/Avery Wizard*/Samples"; DESC="Avery Wizard samples"; add_to_wipe
NAME="$ROAM/avg*/*.log"; DESC="AVG Antivirus"; add_to_delete

# AVG pollution
for X in \
'AVG*/cache' 'AVG*/chjw' 'AVG*/Chjw' 'AVG*/Dumps' 'AVG*/log' \
'AVG*/Log' 'avg*/log' 'avg*/Log' 'avg*/scanlogs' 'avg*/Temp' \
'AVG*/Temp' 'AVG*/SetupBackup' 'AVG*/AWL/CrashDumps' MFAData \
'AVG*/PC Tuneup/Logs' 'AVG*/Rescue';
	do NAME="$ROAM/${X}"; DESC="AVG Antivirus"; add_to_wipe
done

NAME="$ROAM/Avira/AntiVir Desktop/LOGFILES"; DESC="Avira AntiVir"; add_to_wipe
NAME="$ROAM/Avira/AntiVir Desktop/REPORTS"; DESC="Avira AntiVir"; add_to_wipe
NAME="$ROAM/BabSolution"; DESC="Babylon Toolbar"; add_to_wipe
NAME="$ROAM/Babylon"; DESC="Babylon Toolbar"; add_to_wipe
NAME="$ROAM/BabylonToolbar"; DESC="Babylon Toolbar"; add_to_wipe
NAME="$ROAM/Basis Sync/logs"; DESC="Basis Sync logs"; add_to_wipe
NAME="$ROAM/bfgbartb"; DESC="Big Fish Games"; add_to_wipe
NAME="$ROAM/BfgBar"; DESC="Big Fish Games"; add_to_wipe
NAME="$ROAM/Big Fish Games"; DESC="Big Fish Games"; add_to_wipe
NAME="$ROAM/BigFishGamesCache"; DESC="Big Fish Games"; add_to_wipe
NAME="$ROAM/BirdieSync/Log"; DESC="BirdieSync"; add_to_wipe
NAME="$ROAM/Brother/BrLog/*.log"; DESC="Brother logs"; add_to_delete
NAME="$ROAM/BrowserProtect"; DESC="BrowserProtect"; add_to_wipe
NAME="$ROAM/$STARTMENU/BrowserProtect"; DESC="BrowserProtect"; add_to_wipe
NAME="$ROAM/Canon/*/temp"; DESC="Canon"; add_to_wipe
NAME="$ROAM/CitrixLogs"; DESC="Citrix Logs"; add_to_wipe
NAME="$ROAM/ClickPotatoLiteSA"; DESC="ClickPotato"; add_to_wipe
NAME="$ROAM/Complitly"; DESC="Complitly spyware"; add_to_wipe
NAME="$ROAM/Conduit"; DESC="Conduit"; add_to_wipe
NAME="$ROAM/DataMngr"; DESC="DataMngr"; add_to_wipe
NAME="$ROAM/Digital Album Organizer/album/*_cache"; DESC="Digital Album Organizer"; add_to_wipe
NAME="$ROAM/DriverCure"; DESC="DriverCure"; add_to_wipe
NAME="$ROAM/Error*Fix/Logs"; DESC="ErrorFix"; add_to_wipe
NAME="$ROAM/F-Secure/logs"; DESC="F-Secure"; add_to_wipe
NAME="$ROAM/FixCleaner"; DESC="FixCleaner"; add_to_wipe
NAME="$ROAM/File Scout"; DESC="File Scout"; add_to_wipe
NAME="$ROAM/Macromedia/Flash Player"; DESC="Flash cache"; add_to_wipe
NAME="$ROAM/Adobe/Flash Player"; DESC="Flash cache"; add_to_wipe
NAME="$ROAM/Foxit Software/Addon/Install"; DESC="Foxit Addons"; add_to_wipe
NAME="$ROAM/FrostWire/image_cache"; DESC="FrostWire"; add_to_wipe
NAME="$ROAM/FrostWire/azureus/logs"; DESC="FrostWire"; add_to_wipe
NAME="$ROAM/FrostWire/azureus/tmp"; DESC="FrostWire"; add_to_wipe
NAME="$ROAM/FunWebProducts"; DESC="FunWebProducts"; add_to_wipe
NAME="$ROAM/GamesBar"; DESC="GamesBar"; add_to_wipe
NAME="$ROAM/GARMIN/Events"; DESC="Garmin logs"; add_to_wipe
NAME="$ROAM/GARMIN/Logs"; DESC="Garmin logs"; add_to_wipe
NAME="$ROAM/Geek Squad"; DESC="Geek Squad"; add_to_wipe
NAME="$ROAM/Genieo"; DESC="Genieo"; add_to_wipe
NAME="$ROAM/$STARTMENU/Genieo"; DESC="Genieo"; add_to_wipe
NAME="$ROAM/Google/Local Search History"; DESC="Google search history"; add_to_wipe
NAME="$ROAM/Google/Google Toolbar/Update"; DESC="Google Toolbar updates"; add_to_wipe
NAME="$ROAM/grillaprice"; DESC="GorillaPrice"; add_to_wipe
NAME="$ROAM/GTek"; DESC="Dell Support Center"; add_to_wipe
NAME="$ROAM/Gtek"; DESC="Dell Support Center"; add_to_wipe
NAME="$ROAM/HBLiteSA"; DESC="HotBar Lite SA"; add_to_wipe
NAME="$ROAM/Hewlett-Packard/HP Setup/Logs"; DESC="HP temporary files"; add_to_wipe
NAME="$ROAM/Hewlett-Packard/HP Support Framework/Logs"; DESC="HP temporary files"; add_to_wipe
NAME="$ROAM/HP/Installer/Temp"; DESC="HP temporary files"; add_to_wipe
NAME="$ROAM/hpqlog"; DESC="HP temporary files"; add_to_wipe
NAME="$ROAM/IMVU/Cache"; DESC="IMVU"; add_to_wipe
NAME="$ROAM/IMVU/AssetCache"; DESC="IMVU"; add_to_wipe
NAME="$ROAM/IMVU/HttpCache"; DESC="IMVU"; add_to_wipe
NAME="$ROAM/IMVU/PixmapCache"; DESC="IMVU"; add_to_wipe
NAME="$ROAM/IMVU/IMVU*.log*"; DESC="IMVU"; add_to_delete
NAME="$ROAM/InstantSupport"; DESC="Instant Support"; add_to_wipe
NAME="$ROAM/Instant Support"; DESC="Instant Support"; add_to_wipe
NAME="$ROAM/Intuit/Entitlement Client/*/IntuitEntitlementLog.txt*"; DESC="Intuit"; add_to_delete
NAME="$ROAM/Intuit/Intuit Data Protect/QBIDPService.log"; DESC="Intuit"; add_to_delete
NAME="$ROAM/Intuit/Quicken/Log"; DESC="Intuit"; add_to_wipe
NAME="$ROAM/Intuit/QuickBooks*/Components/QBUpdateCache/Patch"; DESC="Intuit"; add_to_wipe
NAME="$ROAM/Intuit/QuickBooks*/Components/Download*/Patch"; DESC="Intuit"; add_to_wipe
NAME="$ROAM/Intuit/QuickBooks*/Components/Download*/*/.update"; DESC="Intuit"; add_to_wipe
NAME="$ROAM/Intuit/QuickBooks DB Server Manager/QBCFMonitorService.log"; DESC="Intuit"; add_to_delete
NAME="$ROAM/Intuit/QuickBooks/qbsdklog.txt"; DESC="Intuit"; add_to_delete
NAME="$ROAM/Intuit/TurboTax/*/ErrorLog"; DESC="Intuit"; add_to_wipe
NAME="$ROAM/IObit"; DESC="IObit"; add_to_wipe
NAME="$ROAM/iWin"; DESC="iWin"; add_to_wipe
NAME="$ROAM/$JAVACACHE"; DESC="Java"; add_to_wipe
NAME="$ROAM/$JSYSCACHE"; DESC="Java"; add_to_wipe
NAME="$ROAM/Juniper Networks/Logging"; DESC="Juniper Networks logs"; add_to_wipe
NAME="$ROAM/Kaspersky Lab/KAV.*.*"; DESC="Kaspersky logs"; add_to_delete
NAME="$ROAM/KeepMySettingsX"; DESC="KeepMySettingsX"; add_to_wipe
NAME="$ROAM/Kodak/Temp"; DESC="Kodak temporary files"; add_to_wipe
NAME="$ROAM/Lavasoft/Web Companion/Logs"; DESC="Lavasoft WC Logs"; add_to_wipe
NAME="$ROAM/Leapfrog/Leapfrog Connect/cache"; DESC="Leapfrog cache"; add_to_wipe
NAME="$ROAM/*.log"; DESC="Miscellanous logs"; add_to_delete
NAME="$ROAM/Logs"; DESC="Miscellanous logs"; add_to_wipe
NAME="$ROAM/LogMeIn"; DESC="LogMeIn logs"; add_to_wipe
NAME="$ROAM/$MBAMLOGS"; DESC="Malwarebytes"; add_to_wipe
NAME="$ROAM/$MBAMQUAR"; DESC="Malwarebytes"; add_to_wipe
NAME="$ROAM/McAfee/Installer/Logs"; DESC="McAfee"; add_to_wipe
NAME="$ROAM/McAfee/MSC/Cache"; DESC="McAfee"; add_to_wipe
NAME="$ROAM/McAfee/MCLOGS"; DESC="McAfee"; add_to_wipe
NAME="$ROAM/McAfee/VirusScan/Quarantine"; DESC="McAfee"; add_to_wipe
NAME="$ROAM/McAfee/*.log"; DESC="McAfee"; add_to_delete
NAME="$ROAM/McAfee/*/*.log"; DESC="McAfee"; add_to_delete
NAME="$ROAM/McAfee/*/*Log.txt"; DESC="McAfee"; add_to_delete
NAME="$ROAM/McAfee.com/*/Logs"; DESC="McAfee"; add_to_wipe
NAME="$ROAM/McAfee.com/*.log"; DESC="McAfee"; add_to_delete
NAME="$ROAM/Move Networks/QMCache00"; DESC="Move Media Player cache"; add_to_wipe
NAME="$ROAM/MP3Rocket/tvimages"; DESC="MP3 Rocket"; add_to_wipe

# Mozilla Firefox/Thunderbird, Pale Moon, etc.
for MOZPROF in "Mozilla" "Mozilla/Firefox" "Thunderbird" \
	"Moonchild Productions/Pale Moon" "LimeWire/mozilla-profile"
	do
	# The LimeWire Mozilla profile doesn't have a Profiles subdirectory
	if [ "$MOZPROF" = "LimeWire/mozilla-profile" ]
		then MOZPROF="$ROAM/$MOZPROF"
		else MOZPROF="$ROAM/$MOZPROF/Profiles/*"
	fi
	DESC="Mozilla applications"
	NAME="$MOZPROF/TestPilotErrorLog.log"; add_to_delete
	NAME="$MOZPROF/Crash Reports"; add_to_wipe
	NAME="$MOZPROF/minidumps"; add_to_wipe
	NAME="$MOZPROF/ConduitEngine"; add_to_delete
	NAME="$MOZPROF/conduit"; add_to_delete
	NAME="$MOZPROF/cookies.sqlite"; add_to_delete
	NAME="$MOZPROF/downloads.sqlite"; add_to_delete
	NAME="$MOZPROF/extensions/*/*/conduit*"; add_to_delete
	NAME="$MOZPROF/extensions/*/*/Conduit*"; add_to_delete
	NAME="$MOZPROF/extensions/*/ffxtlbr@incredibar.com"; add_to_delete
	NAME="$MOZPROF/extensions/*/*/npConduitFirefoxPlugin.dll"; add_to_delete
	NAME="$MOZPROF/extensions/*/*/npPriceGong_FF.dll"; add_to_delete
	NAME="$MOZPROF/extensions/engine@conduit.com"; add_to_delete
	NAME="$MOZPROF/extensions/plugin@yontoo.com"; add_to_delete
	NAME="$MOZPROF/extensions/toolbar@ask.com"; add_to_delete
	NAME="$MOZPROF/Yahoo! Inc/ytoolbar"; add_to_delete
	NAME="$MOZPROF/X*.mfl"; add_to_delete
done
NAME="$ROAM/Mozilla/Firefox/Crash Reports"; DESC="Mozilla applications"; add_to_wipe
NAME="$ROAM/$MOZCNTRL/Cache"; DESC="Mozilla applications"; add_to_wipe
NAME="$ROAM/Mozilla/logs"; DESC="Mozilla applications"; add_to_wipe

NAME="$ROAM/Mozilla/Extensions/SpecialSavings@SpecialSavings.com"; DESC="SpecialSavings"; add_to_wipe
NAME="$ROAM/Mozilla/Extensions/speedanalysis02@SpeedAnalysis.com"; DESC="SpeedAnalysis"; add_to_wipe
NAME="$ROAM/$MS/BingBar"; DESC="Bing Bar"; add_to_wipe
NAME="$ROAM/$MS/CryptnetUrlCache"; DESC="MS crypto cert cache"; add_to_wipe
NAME="$ROAM/$MS/Dr Watson"; DESC="MS app crash dumps"; add_to_wipe
NAME="$ROAM/$MS/eHome/logs"; DESC="Media Center logs"; add_to_wipe
NAME="$ROAM/$MS/IdentityCRL/production/temp"; DESC="MS IdentityCRL temp"; add_to_wipe
NAME="$ROAM/$MS/MSN Messenger"; DESC="MSN Messenger"; add_to_wipe
NAME="$ROAM/$MS/$MS Security */Support/*.log"; DESC="MS Sec Client logs"; add_to_delete
NAME="$ROAM/$MS/Network/Downloader"; DESC="MS Network Downloader"; add_to_wipe
NAME="$ROAM/$MS/Office/Recent"; DESC="MS Office recent docs"; add_to_wipe
NAME="$ROAM/$MS/Search"; DESC="MS Search databases"; add_to_wipe
NAME="$ROAM/$MS/Windows/IECompatCache"; DESC="IE7+ files"; add_to_wipe
NAME="$ROAM/$MS/Windows/IEDownloadHistory"; DESC="IE7+ files"; add_to_wipe
NAME="$ROAM/$MS/Windows/IETldCache"; DESC="IE7+ files"; add_to_wipe
NAME="$ROAM/$MS/Windows/PrivacIE"; DESC="IE7+ files"; add_to_wipe
NAME="$ROAM/$MS/Windows/Power Efficiency Diagnostics/*.xml"; DESC="MS power diag logs"; add_to_delete
NAME="$ROAM/$MS/Windows/Recent"; DESC="Recent documents"; add_to_wipe
NAME="$ROAM/$MS/Windows/Cookies"; DESC="IE cookies"; add_to_wipe
NAME="$ROAM/$MS/Windows/WER/ReportArchive"; DESC="Windows Error Reporting"; add_to_wipe
NAME="$ROAM/$MS/Windows/WER/ReportQueue"; DESC="Windows Error Reporting"; add_to_wipe
NAME="$ROAM/$MS/$WINDEF/Quarantine"; DESC="Windows Defender"; add_to_wipe
NAME="$ROAM/$MS/$WINDEF/Scans"; DESC="Windows Defender"; add_to_wipe
NAME="$ROAM/$MS/$WINDEF/Support"; DESC="Windows Defender"; add_to_wipe
NAME="$ROAM/$MS/WLSetup"; DESC="Windows Live setup"; add_to_wipe
NAME="$ROAM/$MS/Windows Live/Toolbar/Feeds/*.tmp"; DESC="WinLive TB Feeds"; add_to_delete
NAME="$ROAM/$MS/Works SE"; DESC="MS Works SE ad cache"; add_to_wipe
NAME="$ROAM/$MS/Office/*.tmp"; DESC="MS Office temp files"; add_to_delete
NAME="$ROAM/$MS/Word/\~*.tmp"; DESC="MS Office temp files"; add_to_delete
NAME="$ROAM/MyScrapNook*"; DESC="MyScrapNook"; add_to_wipe
NAME="$ROAM/MySpace/IM/SkypeCache"; DESC="MySpaceIM"; add_to_wipe
NAME="$ROAM/MySpace/IM/Images"; DESC="MySpaceIM"; add_to_wipe
NAME="$ROAM/MySpace/*/Logs"; DESC="MySpaceIM"; add_to_wipe
NAME="$ROAM/MyWebSearch"; DESC="MyWebSearch"; add_to_wipe
NAME="$ROAM/NCH Swift Sound/Talk/Logs"; DESC="NCH SS talk logs"; add_to_wipe
NAME="$ROAM/Norton/FSDUI*.log"; DESC="Norton"; add_to_delete
NAME="$ROAM/NortonInstaller"; DESC="Norton"; add_to_wipe
NAME="$ROAM/Norton/LocalDumps"; DESC="Norton"; add_to_delete
NAME="$ROAM/Norton Utilities*/nu.log"; DESC="Norton"; add_to_delete
NAME="$ROAM/Norton Utilities*/log"; DESC="Norton"; add_to_wipe
NAME="$ROAM/OfficeGuardian/\~SACThumbnail"; DESC="OfficeGuardian"; add_to_wipe
NAME="$ROAM/ooVoo Details/cache"; DESC="ooVoo"; add_to_wipe
NAME="$ROAM/ooVoo Details/logs"; DESC="ooVoo"; add_to_wipe
NAME="$ROAM/OpenCandy"; DESC="OpenCandy downloader"; add_to_wipe
NAME="$ROAM/Origin/Logs"; DESC="Origin"; add_to_wipe
NAME="$ROAM/$PARETOAS/*/Logs"; DESC="ParetoLogic logs"; add_to_wipe
NAME="$ROAM/PCAcceleratePro"; DESC="PCAcceleratePro"; add_to_wipe
NAME="$ROAM/PCDr"; DESC="PC-Doctor"; add_to_wipe
NAME="$ROAM/PCFixSpeed"; DESC="PC Fix Speed"; add_to_wipe
NAME="$ROAM/PCPitstop"; DESC="PC Pitstop"; add_to_wipe
NAME="$ROAM/PC Optimizer Pro"; DESC="PC Optimizer Pro"; add_to_wipe
NAME="$ROAM/.pidgin/icons"; DESC="Pidgin messenger"; add_to_wipe
NAME="$ROAM/.purple/icons"; DESC="Pidgin messenger"; add_to_wipe
NAME="$ROAM/$PHOTOEXP/Temp.dat"; DESC="Photo Explosion"; add_to_wipe
NAME="$ROAM/PeoplePC Online/PeoplePC Online Accelerator/temp"; DESC="PeoplePC"; add_to_wipe
NAME="$ROAM/PeoplePC/PeoplePC Fine-Tune"; DESC="PeoplePC"; add_to_wipe
NAME="$ROAM/PictureMover/Log"; DESC="PictureMover"; add_to_wipe
NAME="$ROAM/PictureMover/imageS"; DESC="PictureMover"; add_to_wipe
NAME="$ROAM/PowerChallenge"; DESC="PowerChallenge"; add_to_wipe
NAME="$ROAM/PriceGong"; DESC="PriceGong"; add_to_wipe
NAME="$ROAM/$STARTMENU/PriceGong"; DESC="PriceGong"; add_to_wipe
NAME="$ROAM/Pure Networks/Log"; DESC="Pure Networks logs"; add_to_wipe
NAME="$ROAM/Pure Networks/Platform/MiniDumps"; DESC="Pure Networks dumps"; add_to_wipe
NAME="$ROAM/QuestBrwSearch"; DESC="QuestBrwSearch"; add_to_wipe
NAME="$ROAM/Radialpoint/*.log*"; DESC="Radialpoint Logs"; add_to_delete
NAME="$ROAM/Radialpoint/*/*.log*"; DESC="Radialpoint Logs"; add_to_delete
NAME="$ROAM/Real/*/ErrorLogs"; DESC="RealPlayer"; add_to_wipe
NAME="$ROAM/Real/Msg"; DESC="RealPlayer"; add_to_wipe
NAME="$ROAM/Real/*/DataCache"; DESC="RealPlayer"; add_to_wipe
NAME="$ROAM/Real/Update"; DESC="RealPlayer"; add_to_wipe
NAME="$ROAM/Real/*/temp"; DESC="RealPlayer"; add_to_wipe
NAME="$ROAM/Real/*/Temp"; DESC="RealPlayer"; add_to_wipe
NAME="$ROAM/Real/RealPlayer/db/Backup"; DESC="RealPlayer"; add_to_wipe
NAME="$ROAM/Real/RealPlayer/History"; DESC="RealPlayer"; add_to_wipe
NAME="$ROAM/Real/RealPlayer/ThumbsCache"; DESC="RealPlayer"; add_to_wipe
NAME="$ROAM/Real/RealPlayer/WatchFolders"; DESC="RealPlayer"; add_to_wipe
NAME="$ROAM/Registry Mechanic"; DESC="Registry Mechanic"; add_to_wipe
NAME="$ROAM/Roxio Log Files"; DESC="Roxio Log Files"; add_to_wipe
NAME="$ROAM/$SAFARI/PubSub"; DESC="Safari PubSub data"; add_to_wipe
NAME="$ROAM/SUPERAntiSpyware.com/SUPERAntiSpyware/AppLogs"; DESC="SUPERAntiSpyware logs"; add_to_wipe
NAME="$ROAM/ScanQuery"; DESC="ScanQuery"; add_to_wipe
NAME="$ROAM/SearchDonkey"; DESC="SearchDonkey"; add_to_wipe
NAME="$ROAM/SecondLife/*/browser/_profile/cache"; DESC="SecondLife"; add_to_wipe
NAME="$ROAM/SecondLife/browser_profile/*ache"; DESC="SecondLife"; add_to_wipe
NAME="$ROAM/SecondLife/logs"; DESC="SecondLife"; add_to_wipe
NAME="$ROAM/SHAPE Services/Mobiola WebCamera for iPhone/logs"; DESC="Mobiola logs"; add_to_wipe
NAME="$ROAM/ShopperReports*"; DESC="ShopperReports"; add_to_wipe
NAME="$ROAM/ShoppingReport*"; DESC="ShoppingReport"; add_to_wipe
NAME="$ROAM/Sierra Wireless/Logs"; DESC="Sierra Wireless"; add_to_wipe
NAME="$ROAM/Skype/DbTemp"; DESC="Skype"; add_to_wipe
NAME="$ROAM/Skype/temp-*"; DESC="Skype"; add_to_delete
NAME="$ROAM/Skype/Plugins/Local Cache"; DESC="Skype"; add_to_wipe
NAME="$ROAM/skype.dat"; DESC="VIRUS: skype.dat"; add_to_delete
NAME="$ROAM/SPORE/GraphicsCache*.package"; DESC="SPORE caches"; add_to_delete
NAME="$ROAM/$SPYBOTSD"; DESC="Spybot SnD logs"; add_to_wipe
NAME="$ROAM/Spyware Clear"; DESC="Spyware Clear"; add_to_wipe
NAME="$ROAM/Spyware Terminator"; DESC="Spyware Terminator"; add_to_wipe
NAME="$ROAM/Starware"; DESC="Starware toolbar"; add_to_wipe
NAME="$ROAM/$STARTMENU/Strongvault Online Backup"; DESC="Strongvault Backup"; add_to_wipe
NAME="$ROAM/supportdotcom/logs"; DESC="Support.com logs"; add_to_wipe
NAME="$ROAM/SupportSoft"; DESC="Dell Support Center"; add_to_wipe
NAME="$ROAM/Symantec/Dumps"; DESC="Symantec software"; add_to_wipe
NAME="$ROAM/$SAVCELOGS"; DESC="Symantec software"; add_to_wipe
NAME="$ROAM/Symantec/LiveUpdate/*Log*"; DESC="Symantec software"; add_to_delete
NAME="$ROAM/Symantec/LiveUpdate/Downloads"; DESC="Symantec software"; add_to_wipe
NAME="$ROAM/Syncios/log.txt"; DESC="Syncios log"; add_to_delete
NAME="$ROAM/Systweak"; DESC="Systweak"; add_to_wipe
NAME="$ROAM/TeamViewer/*_logfile.log"; DESC="TeamViewer logs"; add_to_delete
NAME="$ROAM/temp"; DESC="Temporary files (roaming)"; add_to_wipe
NAME="$ROAM/Temp"; DESC="Temporary files (roaming)"; add_to_wipe
NAME="$ROAM/Trend Micro/pc-cillin/Log"; DESC="Trend Micro AV logs"; add_to_wipe
NAME="$ROAM/Toolbar4"; DESC="Toolbar4"; add_to_wipe
NAME="$ROAM/Trusteer/Rapport/logs"; DESC="Trusteer Rapport"; add_to_wipe
NAME="$ROAM/Trusteer/Rapport/user/logs"; DESC="Trusteer Rapport"; add_to_wipe
NAME="$ROAM/Uniblue"; DESC="Uniblue data"; add_to_wipe
NAME="$ROAM/uTorrent/*.torrent"; DESC="uTorrent"; add_to_delete
NAME="$ROAM/utorrent/*.torrent"; DESC="uTorrent"; add_to_delete
NAME="$ROAM/uTorrent/*.old"; DESC="uTorrent"; add_to_delete
NAME="$ROAM/utorrent/*.old"; DESC="uTorrent"; add_to_delete
NAME="$ROAM/uTorrent/dlimagecache"; DESC="uTorrent"; add_to_wipe
NAME="$ROAM/utorrent/dlimagecache"; DESC="uTorrent"; add_to_wipe
NAME="$ROAM/uTorrent/ie"; DESC="uTorrent"; add_to_wipe
NAME="$ROAM/utorrent/ie"; DESC="uTorrent"; add_to_wipe
NAME="$ROAM/Vso/ConvertXtoDVD.log"; DESC="VSO ConvertXtoDVD"; add_to_delete
NAME="$ROAM/Webroot/BugReports"; DESC="Webroot bug reports"; add_to_wipe
NAME="$ROAM/WinClon/Logs"; DESC="WinClon logs"; add_to_wipe
NAME="$ROAM/$WDSMART/*.txt"; DESC="WD SmartWare logs"; add_to_delete
NAME="$ROAM/WindowsSearch/MiniDumps"; DESC="Windows Search minidumps"; add_to_wipe
NAME="$ROAM/Windows Discount"; DESC="FindingDiscount"; add_to_wipe
NAME="$ROAM/Yahoo!/Companion"; DESC="Yahoo Companion"; add_to_wipe

NAME="$P/.thumbnails"; DESC="User thumbnails"; add_to_wipe
NAME="$P/Cookies"; DESC="IE cookies"; add_to_wipe
NAME="$P/CyberLink/CLFaceLogin"; DESC="CyberLink logs"; add_to_wipe
NAME="$P/Music/iTunes/Album Artwork/Cache"; DESC="iTunes caches"; add_to_wipe
NAME="$P/My Documents/My Music/iTunes/Album Artwork/Cache"; DESC="iTunes caches"; add_to_wipe
NAME="$P/Philips/iSite*"; DESC="Philips iSiteLogs"; add_to_wipe
NAME="$P/My Documents/My Pictures/iPod Photo Cache"; DESC="iTunes caches"; add_to_wipe
NAME="$P/Pictures/iPod Photo Cache"; DESC="iTunes caches"; add_to_wipe
NAME="$P/Recent"; DESC="Recent documents"; add_to_wipe
NAME="$P/Incomplete"; DESC="LimeWire incompletes"; add_to_wipe
NAME="$P/IECompatCache"; DESC="IE7 cache"; add_to_wipe
NAME="$P/IETldCache"; DESC="IE7 cache"; add_to_wipe
NAME="$P/PrivacIE"; DESC="IE7 cache"; add_to_wipe
NAME="$P/$XPLS/TEMP"; DESC="XP temporary files"; add_to_wipe
NAME="$P/$XPLS/Temp"; DESC="XP temporary files"; add_to_wipe
NAME="$P/$XPLS/temp"; DESC="XP temporary files"; add_to_wipe
NAME="$P/$XPLS/$TIF"; DESC="TIFs"; add_to_wipe
NAME="$P/$XPLS/History"; DESC="IE History"; add_to_wipe

for FT in amipro.sam excel4.xls lotus.wk4 presenta.shw quattro.wb2 \
	sndrec.wav wordpfct.wpg
	do NAME="$P/Templates/$FT"; DESC="Windows file templates"; add_to_delete
done

NAME="$V7DOCS/$V7SAMPLE"; DESC="Sample media files"; add_to_wipe

# General cleaning

# If no Windows folder was detected, don't try to clean within it
if [ ! "$WINDIR" = "__NONE__" ]
	then
	NAME="$WINDIR/\$NtUninstall*\$"; DESC="Windows Update"; add_to_delete
	NAME="$WINDIR/SoftwareDistribution/Download"; DESC="Windows Update"; add_to_wipe
	NAME="$WINDIR/inf/*.PNF"; DESC="Windows temp files"; add_to_delete
	NAME="$WINTEMP"; DESC="Windows temp files"; add_to_wipe
	NAME="$WINDIR/assembly/*/Temp"; DESC="Windows temp files"; add_to_wipe
	NAME="$WINDIR/SxsCaPendDel"; DESC="Windows temp files"; add_to_delete
	NAME="$WINDIR/*.tmp"; DESC="Windows temp files"; add_to_delete
	NAME="$WINDIR/$SYS32/*.tmp"; DESC="Windows temp files"; add_to_delete
	NAME="$WINDIR/$SYS32/temppf.sys"; DESC="Windows temp files"; add_to_delete
	NAME="$WINDIR/LiveKernelReports/WATCHDOG"; DESC="Windows memory dumps"; add_to_wipe
	NAME="$WINDIR/Minidump"; DESC="Windows memory dumps"; add_to_wipe
	NAME="$WINDIR/MiniDump"; DESC="Windows memory dumps"; add_to_wipe
	NAME="$WINDIR/MEMORY.DMP"; DESC="Windows memory dumps"; add_to_delete
	NAME="$WINDIR/Prefetch"; DESC="Windows prefetcher"; add_to_wipe
	NAME="$WINDIR/$SYS32/FNTCACHE.DAT"; DESC="Windows font cache"; add_to_delete
	NAME="$WINDIR/pchealth/helpctr/OfflineCache/*/*.query"; DESC="Windows Help offline cache"; add_to_delete
	NAME="$WINDIR/Logs"; DESC="Windows logs"; add_to_wipe
	NAME="$WINDIR/ModemLog*.txt"; DESC="Windows logs"; add_to_wipe
	NAME="$WINDIR/security/logs"; DESC="Windows logs"; add_to_wipe
	NAME="$WINDIR/pchealth/helpctr/Logs"; DESC="Windows logs"; add_to_wipe

	# LOTS of Windows log files to delete
	for X in \
	'*.LOG' '*.Log' '*.log' '*.log.*' Debug/blastcln.log \
	'Debug/mrt*.log' Debug/NetSetup.LOG Debug/sammui.log \
	'Debug/UserMode/userenv.*' Debug/WIA/wiatrace.log \
	debug/blastcln.log 'debug/mrt*.log' debug/NetSetup.LOG \
	debug/sammui.log 'debug/UserMode/userenv.*' \
	debug/WIA/wiatrace.log 'inf/setupapi.*.log' 'ModemLog*.txt' \
	Microsoft.NET/Framework*/'*/*.log' 'Panther/*.log' \
	'Panther/UnattendGC/*.log' SchedLgU.Txt ntbtlog.txt \
	'SoftwareDistribution/*.log' sectest.db $SYS32/'*.log' \
	$SYS32/'LogFiles/*/*.log' $SYS32/'LogFiles/*/*.etl' \
	$SYS32/'LogFiles/*/*.etl.*' $SYS32/'Macromed/Flash/*.log' \
	$SYS32/MsDtc/Trace/dtctrace.log $SYS32/'wbem/Logs/*.log' \
	$SYS32/'wbem/Logs/*.lo_' ;
		do NAME="$WINDIR/${X}"; DESC="Windows logs"; add_to_delete
	done

	NAME="$WINDIR/$SYS32/DriverStore/Temp"; DESC="DriverStore temp files"; add_to_wipe
	NAME="$WINDIR/winsxs/Temp"; DESC="WinSxS temporary files"; add_to_wipe
fi

for X in \
RECYCLED RECYCLER Recycled Recycler recycled \
recycler \$Recycle.Bin \$RECYCLE.BIN ;
	do NAME="${X}"; DESC="Recycle Bin"; add_to_wipe
done

NAME="AdobeDebug.txt"; DESC="Adobe debug logs"; add_to_delete
NAME="ADSClient.txt"; DESC="Aluria client files"; add_to_delete
NAME="ADSServer.txt"; DESC="Aluria client files"; add_to_delete
NAME="ADSService.txt"; DESC="Aluria client files"; add_to_delete
NAME="AluriaCacheFile.dat"; DESC="Aluria client files"; add_to_delete
NAME="AI_RecycleBin"; DESC="Advanced Installer files"; add_to_wipe
NAME="\$AVG*"; DESC="AVG virus vault"; add_to_wipe
NAME="found.[0-9][0-9][0-9]"; DESC="CHKDSK fragments"; add_to_wipe
NAME="ffastun*.ff*"; DESC="Find Fast"; add_to_delete
NAME="hp/*.log"; DESC="HP Install Logs"; add_to_delete
NAME="hp/*/*.log"; DESC="HP Install Logs"; add_to_delete
NAME="hp/bin/logs"; DESC="HP Install Logs"; add_to_wipe
NAME="swapfile.sys"; DESC="Paging file"; add_to_delete
NAME="SWAPFILE.SYS"; DESC="Paging file"; add_to_delete
NAME="pagefile.sys"; DESC="Paging file"; add_to_delete
NAME="PAGEFILE.SYS"; DESC="Paging file"; add_to_delete
NAME="hiberfil.sys"; DESC="Hibernation file"; add_to_delete
NAME="HIBERFIL.SYS"; DESC="Hibernation file"; add_to_delete
NAME="SYSTEM.SAV/Logs"; DESC="Miscellaneous logs"; add_to_wipe
NAME="System Volume Information/Chkdsk"; DESC="CHKDSK logs"; add_to_wipe
#NAME="System Volume Information/\{*\}"; DESC="System Restore points"; add_to_delete
#NAME="System Volume Information/_restore*/RP*"; DESC="System Restore points"; add_to_wipe
NAME="sqm*.sqm"; DESC="Stray MSN Msgr files"; add_to_delete
NAME="Temp"; DESC="Temporary files"; add_to_wipe
NAME="temp"; DESC="Temporary files"; add_to_wipe
NAME="TDSSKiller_Quarantine"; DESC="TDSSKiller"; add_to_wipe
# Lots of different log files end up in the root somehow
for X in \
Intel/Logs 'TDSSKiller*_log.txt' '*.log' 'OEM/*.log' 'OEM/*/*.log' \
'OEM/*/*/*.log' 'OEM/*/*/*/*.log' 'OEM/*/*/*/*/*.log' \
ActExtLog.txt logfile logFile.xsl YServer.txt log.txt \
RfLog.txt COMLOG.txt
	do NAME="${X}"; DESC="Log files"; add_to_delete
done
# Some MSVC++ runtime installers barf all over the root of the drive
for X in \
'VC_RED.*' 'eula.*.txt' globdata.ini install.exe \
install.ini 'install.res.*.dll' vcredist.bmp;
	do NAME="${X}"; DESC="MSVC++ installer"; add_to_delete
done

# Load file list in a background process
test $MSG -gt 1 && echo -e "\nLoading file list. Please wait."
find . 2>/dev/null >$TMPFILE

# Scan files
NAME='*.crdownload'; DESC="Partial downloads"; SP='\.'; add_to_scan
NAME='*.partial'; DESC="Partial downloads"; SP='\.'; add_to_scan
NAME='Thumbs\.db'; DESC="Thumbnail DBs"; SP='\.'; add_to_scan
NAME='ehthumbs_vista.db'; DESC="Thumbnail DBs"; SP='\.'; add_to_scan
NAME='\.thumbnails'; DESC="Thumbnails"; SP="\./$P"; add_to_scan
NAME='\~\$[^/]*\.[^/]*'; DESC="Office temp files"; SP='\.'; add_to_scan
NAME='\~WRL[^/]*\.tmp'; DESC="Office temp files"; SP='\.'; add_to_scan
NAME='\~uTorrentPartFile_.*.dat'; DESC="uTorrent part file"; SP='\.'; add_to_scan

# Windows folder viruses
for X in \
sdra64.exe winlogon86.exe \
'TDSS?????*' 'UAC??????*' 'VOID?????*' \
'_VOID?????*' 'PRAGMA???*' 'pragma???*' \
exe.exe svchast.exe nail.exe \
winlgoon.exe iesafemode.exe
	do NAME="${X}"; DESC="KNOWN VIRUS"; SP='\.'; add_to_scan
done

# AppData viruses
for X in \
av.exe ave.exe hotfix.exe virus.exe
	do NAME="${X}"; DESC="KNOWN VIRUS"; SP="\./$P"; add_to_scan
done

rmdir --ignore-fail-on-non-empty "$P/$ROAM/$STARTMENU/*/" "$PD/$STARTMENU/*/" 2>/dev/null

fi
########### End Windows definitions #############

########### Begin Mac OS X definitions #############

if [ $OSX -gt 0 ]; then

# Mozilla Firefox/Thunderbird, Pale Moon, etc.
DESC="Mozilla applications"
for MOZPROFX in Mozilla Mozilla/Firefox Firefox Thunderbird \
	"Moonchild Productions/Pale Moon"
	do
	MOZPROF="$LIBRARY/Application Support/$MOZPROFX/Profiles/*"
	NAME="$MOZPROF/TestPilotErrorLog.log"; add_to_delete
	NAME="$MOZPROF/Crash Reports"; add_to_wipe
	NAME="$MOZPROF/minidumps"; add_to_wipe
	NAME="$MOZPROF/ConduitEngine"; add_to_delete
	NAME="$MOZPROF/conduit"; add_to_delete
	NAME="$MOZPROF/cookies.sqlite"; add_to_delete
	NAME="$MOZPROF/downloads.sqlite"; add_to_delete
	NAME="$MOZPROF/extensions/*/*/conduit*"; add_to_delete
	NAME="$MOZPROF/extensions/*/*/Conduit*"; add_to_delete
	NAME="$MOZPROF/extensions/*/ffxtlbr@incredibar.com"; add_to_delete
	NAME="$MOZPROF/extensions/*/*/npConduitFirefoxPlugin.dll"; add_to_delete
	NAME="$MOZPROF/extensions/*/*/npPriceGong_FF.dll"; add_to_delete
	NAME="$MOZPROF/extensions/engine@conduit.com"; add_to_delete
	NAME="$MOZPROF/extensions/plugin@yontoo.com"; add_to_delete
	NAME="$MOZPROF/extensions/toolbar@ask.com"; add_to_delete
	NAME="$MOZPROF/Yahoo! Inc/ytoolbar"; add_to_delete
	NAME="$MOZPROF/X*.mfl"; add_to_delete

	MOZPROF="$LIBRARY/Caches*/$MOZPROFX/Profiles/*"
	NAME="$MOZPROF/_CACHE_*_"; add_to_delete
	NAME="$MOZPROF/urlclassifier3.sqlite"; add_to_delete
	NAME="$MOZPROF/X*.mfl"; add_to_delete
	NAME="$MOZPROF/minidumps"; add_to_wipe
	NAME="$MOZPROF/thumbnails"; add_to_wipe
	NAME="$MOZPROF/*Cache*"; add_to_wipe
done

NAME="$LIBRARY/Containers/*/Data/Library/Logs"; DESC="Application Logs"; add_to_wipe
NAME="$LIBRARY/Logs/*/"; DESC="Application Logs"; add_to_wipe
NAME="$LIBRARY/Logs/*.*"; DESC="Application Logs"; add_to_delete

fi

############# End Mac OS X definitions ##############


rm -f $TMPFILE

test "$NOSIZE" = "1" && CLEANED="(fast mode)"
test "$MSG" = "1" && echo " $CLEANED KB.${COFF}"
test "$MSG" = "2" && echo -e "\n${CPUR}Completed! ${CGRN}Cleaned ${CWHT}$CLEANED KB.${COFF}\n"

if [ "$XPREDO" = "1" ]
	then
	unset XPREDO
	test $MSG -gt 1 && echo -e "===$CPUR Running in ${CWHT}XP mode$CPUR to catch everything$COFF ===\n"
	$0 $@ --xp --no-report
fi

for X in Windows.old*/ "Restored from Carbonite" Backup* "My Backup*"
	do if [ -d "$X" ]
		then
		test $MSG -gt 1 && echo "Running in subfolder $X"
		CWD="$(pwd)"
		cd "$X"
		if echo "$0" | grep -q '^/'
			then $0 $@ --no-report
			else "$CWD/$0" $@
		fi
		cd "$CWD"
		unset CWD
	fi
done

# Push cleaning action to TSS if possible
A_CLEANER=1
test "$TSS_CLIENT" = "1" && test "$TSS_CLIENT_DISABLE" != "1" && \
	test "$NOREPORT" != "1" && while true
	do
	if push_actions
		then test $MSG -gt 0 && echo "Cleaning reported to TSS successfully."
		break
	fi
	echo "Could not push cleaning report. Check your cables and network connection."
	echo "Press 'x' to abort or any other key to retry."
	read -n 1 -s X
	test "$X" = "x" && echo "Aborting cleaning report push. Use 'tss_push_all' to try again later." && break
done
