#!/bin/sh

echo "Tritech's quick and dirty SSD TRIM utility"

if [ ! -e "$1" ]
	then
	echo "Specify a full device, e.g. /dev/sda"
fi

X=0
while true
	do
	S=$(hdparm --trim-sector-ranges $X:60000 --please-destroy-my-drive "$1" 2>&1 || echo "error")
	echo "$S" | grep -qi -e "SG_IO" -e "No such" -e "error" && echo "$S" && break
	X=$((X + 60000))
	echo -en "Trim $X\r"
done
echo "Finished."
