#!/bin/sh

VER=0.3.1
VERDATE=2014-06-30

test -z "$TSS_COMMON" && . tss__common
test -z "$TSS_COMMON" && echo "tss__common required but failed to load." && exit 1

do_windows_folder_detection
REGSW=__NONE__
REGDIR="$WINDIR/$SYS32/$CONFIG"
for X in $REGDIR/SOFTWARE $REGDIR/software $REGDIR/Software
	do test -e "$X" && REGSW="$X"
done
PRODSPEC=__NONE__
for X in $WINDIR/$SYS32/PRODSPEC.INI $WINDIR/$SYS32/prodspec.ini $WINDIR/$SYS32/Prodspec.ini
	do test -e "$X" && PRODSPEC="$X"
done
test "$REGSW" = "__NONE__" && echo "Cannot find SOFTWARE hive." && exit 3

if mount.winregfs -v 2>/dev/null
	then
	# Use winregfs to read registry data
	TMP=$(mktemp -d || echo "/tmp/foo")
	if ! mount.winregfs "$REGSW" $TMP 2>/dev/null
		then echo "error: cannot mount $REGSW"
		fusermount -u $TMP 2>/dev/null
		rmdir -f $TMP
		exit 1
	fi
	CVER="$(cat "$TMP/Microsoft/Windows NT/CurrentVersion/CurrentVersion.sz")"
	PNAME="$(cat "$TMP/Microsoft/Windows NT/CurrentVersion/ProductName.sz")"
	if [ $(echo "$CVER" | cut -d. -f1) -lt 6 ]
		then EDITION="$(read_inf_section $PRODSPEC "Product Specification" | grep 'Product=' | cut -d' ' -f3- | tr -d \\n | tr -d \\r)"
		else EDITION="$(cat "$TMP/Microsoft/Windows NT/CurrentVersion/EditionID.sz")"
	fi
	fusermount -u $TMP
	rm -rf $TMP
fi

# Fall back to the "old way" if anything went wrong
if [ -z "$CVER" ]
	then
	# Use chntpw's reged to read registry data (slower)
	TMP=$(mktemp)
	reged -x "$REGSW" SOFTWARE 'Microsoft\Windows NT\CurrentVersion' $TMP >/dev/null
	sed -i 's/\\CMI-CreateHive{29EE1162-53C9-4474-A2B6-D90A7F6B0A7C}//g' $TMP
	CVER="$(read_inf_section $TMP 'SOFTWARE\Microsoft\Windows NT\CurrentVersion' | grep -i '"CurrentVersion"=' | cut -d\" -f4)"
	PNAME="$(read_inf_section $TMP 'SOFTWARE\Microsoft\Windows NT\CurrentVersion' | grep -i '"ProductName"=' | cut -d\" -f4)"
	if [ $(echo "$CVER" | cut -d. -f1) -lt 6 ]
		then EDITION="$(read_inf_section $PRODSPEC "Product Specification" | grep 'Product=' | cut -d' ' -f3- | tr -d \\n | tr -d \\r)"
		else EDITION="$(read_inf_section $TMP 'SOFTWARE\Microsoft\Windows NT\CurrentVersion' | grep -i '"EditionID"=' | cut -d\" -f4)"
	fi
	rm -f $TMP
fi

if [ "$SYS64" = "__NONE__" ]
	then WINARCH="ntx86"
	else WINARCH="ntamd64"
fi

WINVER="$WINARCH.$CVER"

case $1 in
"-a")	echo "$PNAME ($WINARCH $CVER $EDITION)"
	break ;;
"-A")	echo "${WINARCH}.${CVER}.$EDITION"
	break ;;
*)	echo "$WINVER"
	break ;;
esac
