#!/bin/sh

echo "TSS wi-fi connect tool (experimental)"
unset IFACE
for INT in /sys/class/net/*/wireless/
	do IFACE="$(basename "$(dirname "$INT")") $IFACE"
done
test -z "$IFACE" && echo "No wireless interfaces available." && exit 1
echo "Detected interfaces: $IFACE"
echo "NOTE: Only supports WPA/WPA2-PSK encrypted networks."
echo -n "Enter network name (SSID): "
read SSID
test -z "$SSID" && echo "Empty SSID not allowed." && exit 1
echo -n "Enter WPA/WPA2-PSK passphrase: "
read PASS

# Unmount CIFS mounts before potentially disconnecting the network
umount -l -t cifs
wpa_passphrase "$SSID" "$PASS" > /etc/wpa.conf
killall wpa_supplicant 2>/dev/null
sleep 0.2
for X in $IFACE
	do
	kill $(pgrep -f 'udhcpc -i $X') 2>/dev/null >/dev/null
	wpa_supplicant -B -Dwext -i$X -c/etc/wpa.conf
	udhcpc -i $X
done
